---

This Notebook creation considered as base this sources

1. Sequence classification Notebook
https://colab.research.google.com/github/huggingface/notebooks/blob/main/transformers_doc/en/pytorch/sequence_classification.ipynb

2. Text Classification Notebook https://colab.research.google.com/github/huggingface/notebooks/blob/main/examples/text_classification.ipynb

3. Tasks: Text Classification guide https://huggingface.co/docs/transformers/en/tasks/sequence_classification

4. Transformers: distilbert model documentation and guide https://huggingface.co/docs/transformers/model_doc/distilbert

5. Create a weighted loss function to handle imbalance? https://discuss.huggingface.co/t/create-a-weighted-loss-function-to-handle-imbalance/138178
---

Citation of the SEAHORSE Dataset:
E. Clark, S. Rijhwani, S. Gehrmann, J. Maynez, R. Aharoni, V. Nikolaev,
T. Sellam, A. Siddhant, D. Das, and A. P. Parikh, “Seahorse: A
multilingual, multifaceted dataset for summarization evaluation,” 2023, GitHub
Website: https://github.com/google-research-datasets/seahorse , HuggingFace
page: https://huggingface.co/datasets/SEACrowd/seahorse. [Online]. Available:
https://arxiv.org/abs/2305.13194

---

# **SEAHORSE Dataset with DestilBert**

In [9]:
# Cell useful for Run all below command

# **1. Set up of environment**

#### **1.1** Install Pytorch with Nvidia CUDA to leverage GPU parallelism.

In [10]:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128

Looking in indexes: https://download.pytorch.org/whl/cu128
Requirement already satisfied: torch in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (2.7.0+cu128)
Requirement already satisfied: torchvision in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (0.22.0+cu128)
Requirement already satisfied: torchaudio in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (2.7.0+cu128)
Requirement already satisfied: filelock in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from torch) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from torch) (4.13.2)
Requirement already satisfied: sympy>=1.13.3 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from torch) (2024.12.0)
Requirement already satisfied: setuptools in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from torch) (79.0.1)
Requirement already satisfied: numpy in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from torchvision) (2.2.5)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from torchvision) (11.2.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from jinja2->torch) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\Aleja\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

#### **1.2** Reproducibility settings.

In [11]:
# Reproducibility configuration

import os

# Deterministic cuBLAS workspace
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"


import torch
import numpy as np
import random
from transformers import set_seed


seed = 42
set_seed(seed)
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
torch.use_deterministic_algorithms(True)

#### **1.3** Install packages and import libraries.

In [12]:
pip install ipython-autotime transformers peft datasets evaluate ipywidgets scikit-learn hf_xet accelerate wget tokenizers accelerate

Requirement already satisfied: ipython-autotime in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (0.3.2)
Requirement already satisfied: transformers in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (4.57.3)
Requirement already satisfied: peft in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (0.18.0)
Requirement already satisfied: datasets in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (4.4.1)
Requirement already satisfied: evaluate in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (0.4.6)
Requirement already satisfied: ipywidgets in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (8.1.8)
Requirement already satisfied: scikit-learn in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: hf_xet in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (1.2.0)
Requirement already satisfied: accelerate in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (1.12.0)
Requirement already satisfied: wget in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (3.2)
Requirement already satisfied: tokenizers in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (0.22.1)
Requirement already satisfied: ipython in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from ipython-autotime) (9.1.0)
Requirement already satisfied: filelock in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from transformers) (2.2.5)
Requirement already satisfied: packaging>=20.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2024.12.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.13.2)
Requirement already satisfied: psutil in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from peft) (7.0.0)
Requirement already satisfied: torch>=1.13.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from peft) (2.7.0+cu128)
Requirement already satisfied: pyarrow>=21.0.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from datasets) (22.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from datasets) (2.2.3)
Requirement already satisfied: httpx<1.0.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.19 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from datasets) (0.70.16)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.11.18)
Requirement already satisfied: anyio in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from httpx<1.0.0->datasets) (4.9.0)
Requirement already satisfied: certifi in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from httpx<1.0.0->datasets) (2025.1.31)
Requirement already satisfied: httpcore==1.* in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from httpx<1.0.0->datasets) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: comm>=0.1.3 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: traitlets>=4.3.1 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from ipywidgets) (5.14.3)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from ipywidgets) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: scipy>=1.10.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.3.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.20.0)
Requirement already satisfied: colorama in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from ipython->ipython-autotime) (0.4.6)
Requirement already satisfied: decorator in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from ipython->ipython-autotime) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from ipython->ipython-autotime) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from ipython->ipython-autotime) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from ipython->ipython-autotime) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from ipython->ipython-autotime) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from ipython->ipython-autotime) (2.19.1)
Requirement already satisfied: stack_data in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from ipython->ipython-autotime) (0.6.3)
Requirement already satisfied: wcwidth in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->ipython-autotime) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from jedi>=0.16->ipython->ipython-autotime) (0.8.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.13.0->peft) (1.13.3)
Requirement already satisfied: networkx in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.13.0->peft) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: setuptools in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.13.0->peft) (79.0.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from jinja2->torch>=1.13.0->peft) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from stack_data->ipython->ipython-autotime) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from stack_data->ipython->ipython-autotime) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\aleja\appdata\local\programs\python\python313\lib\site-packages (from stack_data->ipython->ipython-autotime) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\Aleja\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [13]:
import wget
import zipfile

from datasets import load_dataset,Dataset
from datasets import ClassLabel, Value

import torch
from torch.utils.data import DataLoader

from transformers import DataCollatorWithPadding, AutoTokenizer
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer


import gc

import pandas as pd
import numpy as np

from scipy.stats import pearsonr

import time
import datetime

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

import os
from pathlib import Path
os.environ["WANDB_DISABLED"] = "true"

#### 1.4 Measuring time with CUDA

How to measure Time of execution of a cell using CUDA

```python
start = time.perf_counter()

# code using GPU

torch.cuda.synchronize()
end = time.perf_counter()
elapsed =  end - start
```

In [14]:
# method to print time spent training when obtained elapsed result using cuda
def print_training_time(elapsed):
    print("\n\n________________________________________",
          "Training Time:",
          str(datetime.timedelta(seconds=elapsed)),
          "[" + str(elapsed) + " Seconds]",
          "________________________________________\n", sep="\n")

In [15]:
# method to print time spent training when obtained elapsed result using cuda
def print_inference_time(elapsed):
    print("\n\n________________________________________",
          "Inference Time:",
          str(datetime.timedelta(seconds=elapsed)),
          "[" + str(elapsed) + " Seconds]",
          "________________________________________\n", sep="\n")

#### **1.5** Check that PyTorch uses GPU as Cuda device

In [16]:
from transformers.utils import is_torch_available, is_tf_available, is_flax_available
print("Backends for Hugging Face Transformers Library:")
print("    PyTorch:", is_torch_available())
print("    TensorFlow:", is_tf_available())
print("    JAX/Flax:", is_flax_available())
print()
print("GPU Device =",torch.cuda.is_available()," | ", torch.cuda.get_device_name(0))

Backends for Hugging Face Transformers Library:
    PyTorch: True
    TensorFlow: False
    JAX/Flax: False

GPU Device = True  |  NVIDIA GeForce GTX 1650

Print and save into a text file the environment requirements for replicability

#### **1.6** Save versions of packages and libraries to support future reproducibility.

In [17]:
pip freeze

accelerate==1.12.0
aiohappyeyeballs==2.6.1
aiohttp==3.11.18
aiosignal==1.3.2
anyio==4.9.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==3.0.0
async-lru==2.0.5
attrs==25.3.0
babel==2.17.0
beautifulsoup4==4.13.4
bleach==6.2.0
certifi==2025.1.31
cffi==1.17.1
charset-normalizer==3.4.1
colorama==0.4.6
comm==0.2.2
contourpy==1.3.2
cycler==0.12.1
datasets==4.4.1
debugpy==1.8.14
decorator==5.2.1
defusedxml==0.7.1
dill==0.3.8
evaluate==0.4.6
executing==2.2.0
fastjsonschema==2.21.1
filelock==3.18.0
fonttools==4.57.0
fqdn==1.5.1
frozenlist==1.6.0
fsspec==2024.12.0
graphviz==0.21
h11==0.16.0
hf-xet==1.2.0
httpcore==1.0.9
httpx==0.28.1
huggingface-hub==0.36.0
idna==3.10
ipykernel==6.29.5
ipython==9.1.0
ipython-autotime==0.3.2
ipython_pygments_lexers==1.1.1
ipywidgets==8.1.8
isoduration==20.11.0
jedi==0.19.2
Jinja2==3.1.6
joblib==1.4.2
json5==0.12.0
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2025.4.1
jupyter-events==0.12.0
jupyter-lsp==2.2.5
jupyter_client==8.6.3
jupyter_core==5.7.2
jupyter_server==2.15.0
jupyter_server_terminals==0.5.3
jupyterlab==4.4.1
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.3
jupyterlab_widgets==3.0.16
kiwisolver==1.4.8
MarkupSafe==3.0.2
matplotlib==3.10.1
matplotlib-inline==0.1.7
mistune==3.1.3
MLstatkit==0.1.91
mpmath==1.3.0
multidict==6.4.3
multiprocess==0.70.16
nbclient==0.10.2
nbconvert==7.16.6
nbformat==5.10.4
nest-asyncio==1.6.0
networkx==3.4.2
notebook==7.4.1
notebook_shim==0.2.4
numpy==2.2.5
overrides==7.7.0
packaging==25.0
pandas==2.2.3
pandocfilters==1.5.1
parso==0.8.4
patsy==1.0.2
peft==0.18.0
pillow==11.2.1
platformdirs==4.3.7
prometheus_client==0.21.1
prompt_toolkit==3.0.51
propcache==0.3.1
psutil==7.0.0
pure_eval==0.2.3
pyarrow==22.0.0
pycparser==2.22
Pygments==2.19.1
pyparsing==3.2.3
python-dateutil==2.9.0.post0
python-json-logger==3.3.0
pytz==2025.2
pywin32==310
pywinpty==2.0.15
PyYAML==6.0.2
pyzmq==26.4.0
referencing==0.36.2
regex==2024.11.6
requests==2.32.3
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rpds-py==0.24.0
safetensors==0.5.3
scikit-learn==1.8.0
scipy==1.15.2
Send2Trash==1.8.3
setuptools==79.0.1
six==1.17.0
smart_open==7.5.0
sniffio==1.3.1
soupsieve==2.7
stack-data==0.6.3
statsmodels==0.14.6
sympy==1.13.3
terminado==0.18.1
threadpoolctl==3.6.0
tinycss2==1.4.0
tokenizers==0.22.1
torch==2.7.0+cu128
torchaudio==2.7.0+cu128
torchview==0.2.7
torchvision==0.22.0+cu128
tornado==6.4.2
tqdm==4.67.1
traitlets==5.14.3
transformers==4.57.3
types-python-dateutil==2.9.0.20241206
typing_extensions==4.13.2
tzdata==2025.2
uri-template==1.3.0
urllib3==2.4.0
wcwidth==0.2.13
webcolors==24.11.1
webencodings==0.5.1
websocket-client==1.8.0
wget==3.2
widgetsnbextension==4.0.14
wrapt==2.1.1
xxhash==3.5.0
yarl==1.20.0
Note: you may need to restart the kernel to use updated packages.

In [18]:
pip freeze > requirements.txt

Note: you may need to restart the kernel to use updated packages.

# **2.** Functions to compute performance metrics during training

In [19]:
from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

def compute_model_metrics(predictions_class_1, y_true, threshold_hp = 0.5, print_report=False):
    """
    :param predictions_class_1: Vector of membership probabilities for Class 1 (that instance belongs to class 1).
    :param y_true:  Vector with correct True labels for each sample in dataset.
    :param threshold_hp: A [0-1] custom [>=] threshhold to assign class 1 membership (Optional with default 0.5).
    :param print_report: If true, prints out all computed metrics including the confusion matrix values. If False, returns a dictionary with name and value of metrics. Useful for metrics post epoch evaluation during training.
    """

    assert (0.0 <= threshold_hp <= 1.0), f"Threshold_hp must be a number in range [0-1]"
    y_pred  = (predictions_class_1 >= threshold_hp).long() # Model predicted classification Class-labels
                                                           # long() casts boolean to Int64 in Tensors


    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    accuracy       = accuracy_score(y_true, y_pred)
    precision      = precision_score(y_true, y_pred)
    recall         = recall_score(y_true, y_pred)  # a.k.a. sensitivity
    specificity    = tn / (tn + fp)
    f1             = f1_score(y_true, y_pred)

    youden_j_statistic   = recall + specificity - 1.0
    fpr, tpr, thresholds = roc_curve(y_true, predictions_class_1)
    roc_auc              = auc(fpr, tpr)

    # https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html
    # https://en.wikipedia.org/wiki/Pearson_correlation_coefficient
    pearson_correlation_coefficient, p_value = pearsonr(y_true, predictions_class_1)

    if (print_report):
        print("TN =",tn, "FP =",fp, "FN =",fn, "TP =",tp)
        print(f"Accuracy                  : {accuracy:.4f}", " |",tn + tp, "/" ,tn+fp+fn+tp)
        print(f"Precision                 : {precision:.4f}", " |",tp, "/" ,tp+fp)
        print(f"Sensitivity (Recall, TPR) : {recall:.4f}", " |", tp, "/" ,tp+fn)
        print(f"Specificity (TNR)         : {specificity:.4f}", " |", tn, "/" ,tn+fp) #
        print(f"Youden's J statistic      : {youden_j_statistic:.4f}")
        print(f"ROC AUC                   : {roc_auc:.4f}")
        print(f"Pearson correlation       : r = {pearson_correlation_coefficient:.4f}", f" p = {p_value:.4f}")
        print(f"F1 Score                  : {f1:.4f}")
        return None
    else:
        results = {
        "Accuracy":accuracy,
        "Precision":precision,
        "Sensitivity (Recall, TPR)":recall,
        "Specificity (TNR)":specificity,
        "Youden's J statistic":youden_j_statistic,
        "ROC AUC":roc_auc,
        "Pearson correlation":pearson_correlation_coefficient,
        "F1":f1
        }
        return results

In [20]:
# Metrics to report during training after an epoch completes.
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = torch.from_numpy(predictions) # logits
    softmax_predictions_both_classes = torch.softmax(predictions, dim=1) # Softmax needed for ROC AUC and Pearson correlation
    probabilities_class_1 = softmax_predictions_both_classes[:, 1]
    return compute_model_metrics(probabilities_class_1, torch.from_numpy(labels) )

# **3.** Functions and methods for test set evaluation

In [21]:
def compute_model_predictions(X, pretrained_model_path, data_loader_batch_size = 32, custom_model_class=False):

    #1. Load pretrained model, tokenizer and data loader

    if custom_model_class == "DistilBertDualHeadClassifier":
        model_for_inference = DistilBertDualHeadClassifier.from_pretrained(pretrained_model_path)
    else:
        model_for_inference = AutoModelForSequenceClassification.from_pretrained(
        pretrained_model_path   #"model/checkpoint-123" , dtype=torch.float16
    )



    input_text_tokenizer = AutoTokenizer.from_pretrained(pretrained_model_path)

    #Collate function and dataloader for parallel inference
    def collate_input(batch):
        return input_text_tokenizer(batch, return_tensors="pt", padding=True, truncation=True, max_length=512)

    # Use Dataloader class passing as input a List of strings.
    # This is Ok as List provides all required operations that a Dataset would provide for building a DataLoader
    loader = DataLoader(X, batch_size=data_loader_batch_size, collate_fn=collate_input)



    #2. Perform inference using X data
    #switch pytorch from training mode to evaluation-inference mode. Important to disable train only operations.
    model_for_inference.eval()

    #If available save model in GPU
    inference_device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model_for_inference.to(inference_device)


    all_outputs = []
    with torch.no_grad():
      for inputs in loader:
          inputs = {k: v.to(inference_device) for k, v in inputs.items()} #If available save
                                                                # data in GPU
          logits = model_for_inference(**inputs).logits
          all_outputs.append(logits.detach().cpu())
          del inputs, logits
          torch.cuda.empty_cache()
    gc.collect()
    torch.cuda.empty_cache()
    inference_outputs_tensor = torch.cat(all_outputs, dim=0)


    #switch/restore train mode
    model_for_inference.train()

    return inference_outputs_tensor

In [22]:
def plot_roc_curve(y_true, probabilities):
    # Compute ROC curve
    fpr, tpr, thresholds = roc_curve(y_true, probabilities)
    roc_auc = auc(fpr, tpr)

    # Compute Youden's J statistic
    j_scores = tpr - fpr
    j_max_index = np.argmax(j_scores)
    Youden_threshold = thresholds[j_max_index]

    #balance point
    diff = np.abs(tpr - (1 - fpr))
    balance_index = np.argmin(diff)
    balance_threshold = thresholds[balance_index]

    # Plot ROC
    plt.figure(facecolor='white')
    plt.gca().set_facecolor('white')
    plt.gca().set_aspect('equal', adjustable='box')
    plt.gca()

    plt.plot([0, 1], [0, 1], 'k--') #black dash line

    handle_curve,  = plt.plot(fpr, tpr, label=f'ROC curve (AUC = {roc_auc:.6f})')

    handle_youden = plt.scatter(fpr[j_max_index], tpr[j_max_index], color='magenta',
                                label=f'max Youden J = {Youden_threshold:.6f}')

    handle_balance = plt.scatter(fpr[balance_index], tpr[balance_index], color='green',
                                 label=f'Balance = {balance_threshold:.2f}')

    index_untuned = np.where(thresholds >= 0.5)[0][-1] #thresholds lists in ROC function returned in decreasing order.
    handle_untuned = plt.scatter(fpr[index_untuned], tpr[index_untuned], color='navy',
                                 label=f'Untuned = 0.50')

    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('ROC Curve Thresholds', fontweight='bold')


    ax = plt.gca()
    # First legend (curves)
    legend1 = ax.legend(
        handles=[handle_untuned, handle_youden, handle_balance],
        loc="lower right",
        title="Thresholds"
    )
    ax.add_artist(legend1)   # keep legend1

    legend2 = ax.legend(
        handles=[handle_curve],
        loc="lower right",
        bbox_to_anchor=(1.0, 0.25)
    )

    plt.grid(True)

    os.makedirs("Saved_images", exist_ok=True)
    plt.savefig("Saved_images/roc_curve.png", facecolor='white', dpi=300)


    plt.show()

In [23]:
import re # regular expressions

def sort_files_numerically(file_list):
    """
    Sort a list of Strings using the numbers contained in them.
    Used to sort epochs checkpoints e.g. ['checkpoint-1', 'checkpoint-7', ''checkpoint-20']
    """
    # Extract number from the filename using regex
    def extract_number(filename):
        match = re.search(r'(\d+)', filename)
        return int(match.group(1)) if match else -1

    return sorted(file_list, key=extract_number)

In [24]:
def metrics_reload_model(input_X_data, y_true_labels, model_checkpoint_path, custom_model_class = False):
    """
    Using the folder where a model was saved, compute the metrics.
    """
    logits_predictions = compute_model_predictions(input_X_data, model_checkpoint_path, custom_model_class=custom_model_class)
    softmax_predictions = torch.softmax(logits_predictions, dim=1)  # Softmax for probabilistic interpretation.
    compute_model_metrics(softmax_predictions[:, 1], y_true_labels, print_report=True)

In [25]:
def metrics_all_epochs_post_training(input_X_data, y_true_labels, model_checkpoints_path):
    """
    Using the folder where a model was saved, compute the metrics over the epochs-checkpoints.
    """
    epoch_i = 1
    subfolders = [f for f in os.listdir(model_checkpoints_path) if os.path.isdir(os.path.join(model_checkpoints_path, f))]
    subfolders = sort_files_numerically(subfolders)

    for model_checkpoint in subfolders:

        print("\nEpoch " + str(epoch_i),"[" + model_checkpoint + "]")
        epoch_i += 1

        logits_predictions = compute_model_predictions(input_X_data, model_checkpoints_path + "/" +  model_checkpoint)
        softmax_predictions = torch.softmax(logits_predictions, dim=1) # Softmax for probabilistic interpretation.
        compute_model_metrics(softmax_predictions[:, 1], y_true_labels, print_report=True)

In [26]:
def obtain_language_separated_subdatasets(Dataset_object):
    languages = Dataset_object.unique("language")
    language_separated_datasets = {}
    for language in languages:
        filtered = Dataset_object.filter(lambda row: row["language"] == language)
        language_separated_datasets[language] = filtered
    return language_separated_datasets

In [27]:
def assess_per_language_performance(Dataset_object, model_path):
    language_separated_datasets = obtain_language_separated_subdatasets(Dataset_object)
    for language, subdataset_language_i in language_separated_datasets.items():
        logits_predictions_language_i = compute_model_predictions(subdataset_language_i["text"], model_path)
        softmax_predictions_class_1 = torch.softmax(logits_predictions_language_i, dim=1)
        print("Language:", language)
        compute_model_metrics(softmax_predictions_class_1[:, 1], subdataset_language_i["labels"])
        print()

# **4.** Load data

## **4.1** Training and validation data

We start loading the preprocessed data (See the `Data_preparation.ipynb` Notebook).

The datasets we pass to Trainer must have their target column named as `"labels"`

In [28]:
comprehensible_train_dataframe      = pd.read_csv("unbalanced_seahorse/seahorse_dataset_train_df_unbalanced.csv")
comprehensible_validation_dataframe = pd.read_csv("unbalanced_seahorse/seahorse_dataset_validation_df_unbalanced.csv")
Dataset_object_comprehensible_train      = Dataset.from_pandas(comprehensible_train_dataframe).rename_column("comprehensible", "labels")
Dataset_object_comprehensible_validation = Dataset.from_pandas(comprehensible_validation_dataframe).rename_column("comprehensible", "labels")

grammar_train_dataframe      = pd.read_csv("unbalanced_seahorse/seahorse_dataset_train_df_subset_comprehensible_is_yes_unbalanced.csv")
grammar_validation_dataframe = pd.read_csv("unbalanced_seahorse/seahorse_dataset_validation_df_subset_comprehensible_is_yes_unbalanced.csv")
Dataset_object_grammar_train      = Dataset.from_pandas(grammar_train_dataframe).rename_column("grammatical", "labels")
Dataset_object_grammar_validation = Dataset.from_pandas(grammar_validation_dataframe).rename_column("grammatical", "labels")

repetition_train_dataframe      = pd.read_csv("unbalanced_seahorse/seahorse_dataset_train_df_subset_comprehensible_is_yes_unbalanced.csv")
repetition_validation_dataframe = pd.read_csv("unbalanced_seahorse/seahorse_dataset_validation_df_subset_comprehensible_is_yes_unbalanced.csv")
Dataset_object_repetition_train      = Dataset.from_pandas(repetition_train_dataframe).rename_column("repetition_free", "labels")
Dataset_object_repetition_validation = Dataset.from_pandas(repetition_validation_dataframe).rename_column("repetition_free", "labels")

Target-Label column must be of type `Int64` for Classification models.

In [29]:
Dataset_object_comprehensible_train      = Dataset_object_comprehensible_train.cast_column("labels", Value("int64"))
Dataset_object_comprehensible_validation = Dataset_object_comprehensible_validation.cast_column("labels", Value("int64"))

Dataset_object_grammar_train      = Dataset_object_grammar_train.cast_column("labels", Value("int64"))
Dataset_object_grammar_validation = Dataset_object_grammar_validation.cast_column("labels", Value("int64"))

Dataset_object_repetition_train      = Dataset_object_repetition_train.cast_column("labels", Value("int64"))
Dataset_object_repetition_validation = Dataset_object_repetition_validation.cast_column("labels", Value("int64"))

Casting the dataset:   0%|          | 0/60470 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/8895 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/54566 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/8025 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/54566 [00:00<?, ? examples/s]

Casting the dataset:   0%|          | 0/8025 [00:00<?, ? examples/s]

Apply Tokenization

In [30]:
# Tokenizer and Collator to use whenever data require processing to fit format or batch sizes.
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-multilingual-cased")

#collator with padding allows to adjust dynamically each batch sample to the max batch length, for correct parallelization.
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

In [31]:
def preprocess_function(examples):
    return tokenizer(examples["text"], truncation=True) # In each row the name of field is text

In [32]:
tokenized_comprehensible_train = Dataset_object_comprehensible_train.map(preprocess_function, batched=True)
tokenized_comprehensible_validation = Dataset_object_comprehensible_validation.map(preprocess_function, batched=True)

tokenized_grammar_train = Dataset_object_grammar_train.map(preprocess_function, batched=True)
tokenized_grammar_validation = Dataset_object_grammar_validation.map(preprocess_function, batched=True)

tokenized_repetition_train = Dataset_object_repetition_train.map(preprocess_function, batched=True)
tokenized_repetition_validation = Dataset_object_repetition_validation.map(preprocess_function, batched=True)

Map:   0%|          | 0/60470 [00:00<?, ? examples/s]

Map:   0%|          | 0/8895 [00:00<?, ? examples/s]

Map:   0%|          | 0/54566 [00:00<?, ? examples/s]

Map:   0%|          | 0/8025 [00:00<?, ? examples/s]

Map:   0%|          | 0/54566 [00:00<?, ? examples/s]

Map:   0%|          | 0/8025 [00:00<?, ? examples/s]

## **4.2** Test data

For robust evaluation we avoided preprocessing the test data.

We perform the minimal modifications needed for test set to be run in the model:

* In SEAHORSE only rows considered comprehensible were further annotated for repetition_free and grammatical. Therefore, Apply a filter.
* Change the label format `No:0 Yes:1`.
* Remove rows WITH `Unsure` rating.
Not any preprocessing applied to test set. Tokenization will be done at inference time.
We load the Xs texts and y labels directly from the original dataset.

In [33]:
# In case we already have the dataset file, we skip download+extract.
file_path = Path("seahorse_data.zip")
if not file_path.is_file():
    url = "https://storage.googleapis.com/seahorse-public/seahorse_data.zip"
    filename = wget.download(url)
    with zipfile.ZipFile("seahorse_data.zip", 'r') as zip_ref:
        zip_ref.extractall()

In [34]:
seahorse_dataset = load_dataset(
    "csv",
    data_files = {
        "train": "seahorse_data/train.tsv",
        "validation": "seahorse_data/validation.tsv",
        "test": "seahorse_data/test.tsv"
    },
    delimiter="\t"
)

In [35]:
test_data = seahorse_dataset["test"].to_pandas()
test_data.replace({'No': 0, 'Yes': 1}, inplace=True)

X_test    = test_data["summary"]
test_comprehensible    =   test_data[~( (test_data["question1"] == "Unsure") )]
X_test_comprehensible    = test_comprehensible["summary"]
y_test_comprehensible    = test_comprehensible["question1"]

test_repetition_free     = test_data[( (test_data["question1"] == 1) & ~(test_data["question2"] == "Unsure") )]
X_test_repetition_free   = test_repetition_free["summary"]
y_test_repetition_free   = test_repetition_free["question2"]

test_grammatical     = test_data[( (test_data["question1"] == 1) & ~(test_data["question3"] == "Unsure") )]
X_test_grammatical   = test_grammatical["summary"]
y_test_grammatical   = test_grammatical["question3"]

# **5.** Weighted Loss

We use weighted error to manage Class imbalance. This preserves the diversity of majority class observations.

#### **5.1** Compute class weights using inverse frequency and then normalization.

In [36]:
from collections import Counter
print("                           0       1    ")

print("Comprehensible:")

label_counts = Counter(tokenized_comprehensible_train["labels"])
num_classes = 2
class_counts = torch.tensor([label_counts[i] for i in range(num_classes)], dtype=torch.float)

inverse_frequency_class_weights_comprehensible = 1.0 / class_counts        # inverse frequency
inverse_frequency_class_weights_comprehensible = (inverse_frequency_class_weights_comprehensible /
                                                  inverse_frequency_class_weights_comprehensible.sum())  # optional normalization

print("class counts:  ",  class_counts)
print("class weights: ", inverse_frequency_class_weights_comprehensible)


print("\nRepetition_free:")

label_counts = Counter(tokenized_repetition_train["labels"])
num_classes = 2
class_counts = torch.tensor([label_counts[i] for i in range(num_classes)], dtype=torch.float)

inverse_frequency_class_weights_repetition = 1.0 / class_counts        # inverse frequency
inverse_frequency_class_weights_repetition = (inverse_frequency_class_weights_repetition /
                                              inverse_frequency_class_weights_repetition.sum())  # optional normalization

print("class counts:  ",  class_counts)
print("class weights: ", inverse_frequency_class_weights_repetition)



print("\nGrammatical:")

label_counts = Counter(tokenized_grammar_train["labels"])
num_classes = 2
class_counts = torch.tensor([label_counts[i] for i in range(num_classes)], dtype=torch.float)

inverse_frequency_class_weights_grammar = 1.0 / class_counts        # inverse frequency
inverse_frequency_class_weights_grammar = (inverse_frequency_class_weights_grammar /
                                              inverse_frequency_class_weights_grammar.sum())  # optional normalization

print("class counts:  ",  class_counts)
print("class weights: ", inverse_frequency_class_weights_grammar)

                           0       1
Comprehensible:
class counts:   tensor([ 5904., 54566.])
class weights:  tensor([0.9024, 0.0976])

Repetition_free:
class counts:   tensor([ 6124., 48442.])
class weights:  tensor([0.8878, 0.1122])

Grammatical:
class counts:   tensor([ 5557., 49009.])
class weights:  tensor([0.8982, 0.1018])

#### **5.2** Extend the Trainer class to use weighted Cross Entropy Loss

We pass all basic trainer parameters, and now also the weights.

```python
trainer = WeightedCrossEntropyTrainer(
    ...
    class_weights=class_weights
)
```

In [37]:
from transformers import Trainer
import torch
import torch.nn as nn

class WeightedCrossEntropyTrainer(Trainer):
    def __init__(self, *args, class_weights=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.class_weights = class_weights  # tensor, shape [2]

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")  # integer labels: 0 or 1
        outputs = model(**inputs)
        logits = outputs.logits  # shape [batch, 2]

        loss = None
        if labels is not None:
            loss_fn = nn.CrossEntropyLoss(weight=self.class_weights.to(logits.device))
            loss = loss_fn(logits.view(-1, 2), labels.view(-1))

        return (loss, outputs) if return_outputs else loss

# **6.** Methods for freezing layers

In [38]:
def show_trainable_and_frozen(model):
    for name, param in model.named_parameters():
        if param.requires_grad:
            print("Trainable:", name)
        else:
            print("Frozen:", name)

In [39]:
def freeze_first_n_layers(model, n):
    for param in model.distilbert.embeddings.parameters():
        param.requires_grad = False
    layers = model.distilbert.transformer.layer
    for layer in layers[:n]:
        for param in layer.parameters():
            param.requires_grad = False

In [40]:
# Freeze all backbone parameters
def freeze_all_destilbert(model):
    for param in model.distilbert.parameters():
        param.requires_grad = False

holi

# Custom Fusion classifiers

##### DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

In [41]:
from transformers.modeling_outputs import SequenceClassifierOutput
import torch.nn as nn
from transformers import DistilBertModel, DistilBertPreTrainedModel
from torch.nn import GELU

class DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(DistilBertPreTrainedModel):
    def __init__(self, config):
        super().__init__(config)
        self.num_labels = config.num_labels
        self.distilbert = DistilBertModel(config)


        self.cls_head = nn.Sequential(
            nn.Linear(config.dim, 768),
            nn.GELU(),
            nn.Dropout(config.seq_classif_dropout),
        )

        self.avg_head = nn.Sequential(
            nn.Linear(config.dim, 768),
            nn.GELU(),
            nn.Dropout(config.seq_classif_dropout),
        )

        self.merge_classifier = nn.Linear(768, config.num_labels)

        self.post_init()

    def avg_pooling(self, hidden_states, attention_mask):
        mask = attention_mask.clone()
        mask[:, 0] = 0  # remove CLS

        mask_expanded = mask.unsqueeze(-1).expand(hidden_states.size()).float()
        sum_embeddings = torch.sum(hidden_states * mask_expanded, dim=1)
        sum_mask = torch.clamp(mask_expanded.sum(dim=1), min=1e-9)

        return sum_embeddings / sum_mask



    def forward(
        self,
        input_ids=None,
        attention_mask=None,
        labels=None,
        **kwargs
    ):
        bert_kwargs = {k: v for k, v in kwargs.items() if k in ["output_hidden_states", "output_attentions"]}

        return_dict = kwargs.pop("return_dict", True)
        outputs = self.distilbert(
            input_ids=input_ids,
            attention_mask=attention_mask,
            return_dict=return_dict,
            **bert_kwargs
        )

        hidden_states = outputs.last_hidden_state  # (batch_size, seq_len, 768)

        # Branch 1: [CLS] token
        cls_output = hidden_states[:, 0, :]         # for all batch take [CLS] complete.
        cls_branch = self.cls_head(cls_output)

        # Branch 2: Average pooling
        avg_output = self.avg_pooling(hidden_states, attention_mask)
        avg_branch = self.avg_head(avg_output)

        # Merge and classify
        #merged = torch.cat([cls_branch, avg_branch], dim=1)
        merged = cls_branch + avg_branch   # (B, 768)
        logits = self.merge_classifier(merged)

        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()
            loss = loss_fct(logits, labels)

        return SequenceClassifierOutput(
            loss=loss,
            logits=logits,
            hidden_states = None, # =outputs.hidden_states,
            attentions    = None, # outputs.attentions,
                )

```
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)
````

##### DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

In [42]:
from transformers.modeling_outputs import SequenceClassifierOutput
import torch.nn as nn
from transformers import DistilBertModel, DistilBertPreTrainedModel
from torch.nn import GELU

class DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(DistilBertPreTrainedModel):
    def __init__(self, config):
        super().__init__(config)
        self.num_labels = config.num_labels
        self.distilbert = DistilBertModel(config)

        self.merge_classifier = nn.Sequential(
            nn.Linear(1536, 768),
            nn.GELU(),
            nn.Dropout(config.seq_classif_dropout),
            nn.Linear(768, 2)
        )

        self.post_init()

    def avg_pooling(self, hidden_states, attention_mask):
        mask = attention_mask.clone()
        mask[:, 0] = 0  # remove CLS

        mask_expanded = mask.unsqueeze(-1).expand(hidden_states.size()).float()
        sum_embeddings = torch.sum(hidden_states * mask_expanded, dim=1)
        sum_mask = torch.clamp(mask_expanded.sum(dim=1), min=1e-9)

        return sum_embeddings / sum_mask



    def forward(
        self,
        input_ids=None,
        attention_mask=None,
        labels=None,
        **kwargs
    ):
        bert_kwargs = {k: v for k, v in kwargs.items() if k in ["output_hidden_states", "output_attentions"]}

        return_dict = kwargs.pop("return_dict", True)
        outputs = self.distilbert(
            input_ids=input_ids,
            attention_mask=attention_mask,
            return_dict=return_dict,
            **bert_kwargs
        )

        hidden_states = outputs.last_hidden_state  # (batch_size, seq_len, 768)

        # Branch 1: [CLS] token
        cls_output = hidden_states[:, 0, :]         # for all batch take [CLS] complete.
        # Branch 2: Average pooling
        avg_output = self.avg_pooling(hidden_states, attention_mask)

        # Merge and classify
        merged = torch.cat([cls_output, avg_output], dim=1)
        logits = self.merge_classifier(merged)

        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()
            loss = loss_fct(logits, labels)

        return SequenceClassifierOutput(
            loss=loss,
            logits=logits,
            hidden_states = None, # outputs.hidden_states,
            attentions    = None, # outputs.attentions,
                )

```
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)
```

##### Feature extraction as CLS and average pool soncatenations of last 3 layers

In [43]:
from transformers import DistilBertModel, DistilBertPreTrainedModel, DistilBertConfig
from transformers.modeling_outputs import SequenceClassifierOutput
import torch
import torch.nn as nn
from torch.nn import GELU

class DistilBertLast3LayerFusion(DistilBertPreTrainedModel):
    def __init__(self, config):
        super().__init__(config)
        self.num_labels = config.num_labels
        self.distilbert = DistilBertModel(config)

        # Hidden dimension for DistilBERT
        hidden_dim = config.dim
        # Last 3 layers concatenation → 3 * hidden_dim
        self.feature_dim = hidden_dim * 3  # per branch (CLS or mean)

        # Fusion head: input = CLS + Mean pooling concatenated → 2*feature_dim
        self.merge_classifier = nn.Sequential(
            nn.Linear(self.feature_dim * 2, 1024),  # possible to set smaller/larger
            GELU(),
            nn.Dropout(config.seq_classif_dropout),
            nn.Linear(1024, config.num_labels)
        )

        self.post_init()

    # Safe mean pooling ignoring CLS token
    def mean_pooling(self, hidden_states, attention_mask):
        mask = attention_mask.clone()
        mask[:, 0] = 0  # ignore CLS

        mask_exp = mask.unsqueeze(-1).expand(hidden_states.size()).float()
        sum_emb = torch.sum(hidden_states * mask_exp, dim=1)
        sum_mask = torch.clamp(mask_exp.sum(dim=1), min=1e-9)
        return sum_emb / sum_mask

    def forward(self, input_ids=None, attention_mask=None, labels=None, **kwargs):
        # Safe handling of return_dict to avoid multiple keyword error
        return_dict = kwargs.pop("return_dict", True)

        # Extract hidden states and attentions keys from kwargs
        bert_kwargs = {k: v for k, v in kwargs.items() if k in ["output_hidden_states", "output_attentions"]}

        outputs = self.distilbert(
            input_ids=input_ids,
            attention_mask=attention_mask,
            output_hidden_states=True,
            return_dict=return_dict,
            **bert_kwargs
        )

        hidden_states = outputs.hidden_states  # tuple: (embeddings, layer1, ..., layer6)
        # Grab last 3 layers
        last_3 = hidden_states[-3:]  # tuple of 3 tensors

        # ---- Branch 1: CLS token concatenation ----
        cls_features = torch.cat([layer[:, 0, :] for layer in last_3], dim=1)  # (batch, 3*hidden_dim)

        # ---- Branch 2: Mean pooling of last 3 layers ----
        mean_features = torch.cat([self.mean_pooling(layer, attention_mask) for layer in last_3], dim=1)  # (batch, 3*hidden_dim)

        # ---- Merge both branches ----
        fusion_features = torch.cat([cls_features, mean_features], dim=1)  # (batch, 2*feature_dim)

        logits = self.merge_classifier(fusion_features)

        loss = None
        if labels is not None:
            loss_fct = nn.CrossEntropyLoss()
            loss = loss_fct(logits, labels)

        return SequenceClassifierOutput(
            loss=loss,
            logits=logits,
            hidden_states = None, # hidden_states=outputs.hidden_states,
            attentions    = None # attentions=outputs.attentions
        )

# **Bookmark: Run all needed before training models**

In [44]:
# This cell will appear as executed

In [37]:
# In this cell do Run all above

# 1. Initial  Exploration

# Fine Tuning of Last 3 layers (one hidden layer for [CLS] representation)

#### HuggingFace DistilBertForSequenceClassification Model


Now we createas baseline a basic DistilBert Classifier as shown in the referenced materials (see start of notebook).

HuggingFace provides the function `AutoModelForSequenceClassification`. When it is applied to _**distilbert-base-multilingual-cased**_ for a Binary/2-Class Classification problem, it creates a `DistilBertForSequenceClassification` model.

The Classification Head of this model is as follows:

*768 Units with ReLU Activation and Dropout(p=0.2) `[input features = 768, units/output features = 768]`
*2 units with Linear output `[input features = 768, units/output features = 2]`

Note also that this model will automatically use CrossEntropyLoss() as Loss function.


The source code of this HuggingFace model can be found at:

https://github.com/huggingface/transformers/blob/v4.57.3/src/transformers/models/distilbert/modeling_distilbert.py#L851

To correctly understand the architecture is important to check both the named-attribute layers and the forward pass function to see the activation functions. Note that here if we use the print function for the model we don't see the ReLu activation applied.

## Comprehensible_DBSC_FT_3_layers

In [38]:
Comprehensible_DBSC_FT_3_layers = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-multilingual-cased",
    num_labels=2
)
#A warning is displayed because Head aimed for fine tuning has not yet weights.

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Comprehensible_DBSC_FT_3_layers) # See notes above on why ReLU activation does not show.

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

Keep only last 3 layers trainable

In [40]:
freeze_first_n_layers(Comprehensible_DBSC_FT_3_layers,3)

In [42]:
show_trainable_and_frozen(Comprehensible_DBSC_FT_3_layers)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Trainable: distilbert.transformer.layer.3.attention.q_lin.weight
Trainable: distilbert.transformer.layer.3.attention.q_lin.bias
Trainable: distilbert.transformer.layer.3.attention.k_lin.weight
Trainable: distilbert.transformer.layer.3.attention.k_lin.bias
Trainable: distilbert.transformer.layer.3.attention.v_lin.weight
Trainable: distilbert.transformer.layer.3.attention.v_lin.bias
Trainable: distilbert.transformer.layer.3.attention.out_lin.weight
Trainable: distilbert.transformer.layer.3.attention.out_lin.bias
Trainable: distilbert.transformer.layer.3.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.3.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.3.ffn.lin1.weight
Trainable: distilbert.transformer.layer.3.ffn.lin1.bias
Trainable: distilbert.transformer.layer.3.ffn.lin2.weight
Trainable: distilbert.transformer.layer.3.ffn.lin2.bias
Trainable: distilbert.transformer.layer.3.output_layer_norm.weight
Trainable: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: pre_classifier.weight
Trainable: pre_classifier.bias
Trainable: classifier.weight
Trainable: classifier.bias

Train the model

In [43]:
training_args_Comprehensible_DBSC_FT_3_layers = TrainingArguments(

    output_dir                 = "Saved_models/Comprehensible_DBSC_FT_3_layers",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DBSC_FT_3_layers_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DBSC_FT_3_layers,
    args              = training_args_Comprehensible_DBSC_FT_3_layers,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [44]:
training_args_Comprehensible_DBSC_FT_3_layers

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Comprehensible_DBSC_FT_3_layers\runs\Jan30_10-31-44_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Comprehensible_DBSC_FT_3_layers,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [45]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DBSC_FT_3_layers.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DBSC_FT_3_layers_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
6:12:21.138774
[22341.138774199877 Seconds]
________________________________________

## Repetition_free_DBSC_FT_3_layers

In [38]:
Repetition_free_DBSC_FT_3_layers = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-multilingual-cased",
    num_labels=2
)
#A warning is displayed because Head aimed for fine tuning has not yet weights.

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Repetition_free_DBSC_FT_3_layers) # See notes above on why ReLU activation does not show.

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

Keep only last 3 layers trainable

In [40]:
freeze_first_n_layers(Repetition_free_DBSC_FT_3_layers,3)

In [41]:
show_trainable_and_frozen(Repetition_free_DBSC_FT_3_layers)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Trainable: distilbert.transformer.layer.3.attention.q_lin.weight
Trainable: distilbert.transformer.layer.3.attention.q_lin.bias
Trainable: distilbert.transformer.layer.3.attention.k_lin.weight
Trainable: distilbert.transformer.layer.3.attention.k_lin.bias
Trainable: distilbert.transformer.layer.3.attention.v_lin.weight
Trainable: distilbert.transformer.layer.3.attention.v_lin.bias
Trainable: distilbert.transformer.layer.3.attention.out_lin.weight
Trainable: distilbert.transformer.layer.3.attention.out_lin.bias
Trainable: distilbert.transformer.layer.3.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.3.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.3.ffn.lin1.weight
Trainable: distilbert.transformer.layer.3.ffn.lin1.bias
Trainable: distilbert.transformer.layer.3.ffn.lin2.weight
Trainable: distilbert.transformer.layer.3.ffn.lin2.bias
Trainable: distilbert.transformer.layer.3.output_layer_norm.weight
Trainable: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: pre_classifier.weight
Trainable: pre_classifier.bias
Trainable: classifier.weight
Trainable: classifier.bias

Train the model

In [42]:
training_args_Repetition_free_DBSC_FT_3_layers = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_free_DBSC_FT_3_layers",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_free_DBSC_FT_3_layers_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_free_DBSC_FT_3_layers,
    args              = training_args_Repetition_free_DBSC_FT_3_layers,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_free_DBSC_FT_3_layers.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_free_DBSC_FT_3_layers_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
5:01:27.881940
[18087.88194030011 Seconds]
________________________________________

## Grammatical_DBSC_FT_3_layers

In [38]:
Grammatical_DBSC_FT_3_layers = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-multilingual-cased",
    num_labels=2
)
#A warning is displayed because Head aimed for fine tuning has not yet weights.

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Grammatical_DBSC_FT_3_layers) # See notes above on why ReLU activation does not show.

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

Keep only last 3 layers trainable

In [40]:
freeze_first_n_layers(Grammatical_DBSC_FT_3_layers,3)

In [41]:
show_trainable_and_frozen(Grammatical_DBSC_FT_3_layers)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Trainable: distilbert.transformer.layer.3.attention.q_lin.weight
Trainable: distilbert.transformer.layer.3.attention.q_lin.bias
Trainable: distilbert.transformer.layer.3.attention.k_lin.weight
Trainable: distilbert.transformer.layer.3.attention.k_lin.bias
Trainable: distilbert.transformer.layer.3.attention.v_lin.weight
Trainable: distilbert.transformer.layer.3.attention.v_lin.bias
Trainable: distilbert.transformer.layer.3.attention.out_lin.weight
Trainable: distilbert.transformer.layer.3.attention.out_lin.bias
Trainable: distilbert.transformer.layer.3.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.3.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.3.ffn.lin1.weight
Trainable: distilbert.transformer.layer.3.ffn.lin1.bias
Trainable: distilbert.transformer.layer.3.ffn.lin2.weight
Trainable: distilbert.transformer.layer.3.ffn.lin2.bias
Trainable: distilbert.transformer.layer.3.output_layer_norm.weight
Trainable: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: pre_classifier.weight
Trainable: pre_classifier.bias
Trainable: classifier.weight
Trainable: classifier.bias

Train the model

In [42]:
training_args_Grammatical_DBSC_FT_3_layers = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_DBSC_FT_3_layers",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DBSC_FT_3_layers_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DBSC_FT_3_layers,
    args              = training_args_Grammatical_DBSC_FT_3_layers,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
training_args_Grammatical_DBSC_FT_3_layers

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_DBSC_FT_3_layers\runs\Jan30_02-17-44_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_DBSC_FT_3_layers,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [44]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DBSC_FT_3_layers.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DBSC_FT_3_layers_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
5:00:11.172091
[18011.172091499902 Seconds]
________________________________________

# Feature extraction (last 3 layer embeddings)

## Comprehensible

In [38]:
Comprehensible_DistilBertLast3LayerFusion_config = DistilBertConfig.from_pretrained(
                                                    "distilbert-base-multilingual-cased",
                                                    num_labels=2,
                                                    dropout=0.1,
                                                    attention_dropout=0.1,
                                                    seq_classif_dropout=0.1,
                                                )

Comprehensible_DistilBertLast3LayerFusion_model = DistilBertLast3LayerFusion.from_pretrained(
    "distilbert-base-multilingual-cased",
    config=Comprehensible_DistilBertLast3LayerFusion_config,
    ignore_mismatched_sizes=True  # important for custom head
)

Some weights of DistilBertLast3LayerFusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Comprehensible_DistilBertLast3LayerFusion_model) # See notes above on why ReLU activation does not show.

DistilBertLast3LayerFusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=4608, out_features=1024, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=1024, out_features=2, bias=True)
  )
)

Freeze all DestilBERT. We use only as Feature Extractor.

In [40]:
freeze_all_destilbert(Comprehensible_DistilBertLast3LayerFusion_model)

In [41]:
show_trainable_and_frozen(Comprehensible_DistilBertLast3LayerFusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Frozen: distilbert.transformer.layer.4.attention.q_lin.weight
Frozen: distilbert.transformer.layer.4.attention.q_lin.bias
Frozen: distilbert.transformer.layer.4.attention.k_lin.weight
Frozen: distilbert.transformer.layer.4.attention.k_lin.bias
Frozen: distilbert.transformer.layer.4.attention.v_lin.weight
Frozen: distilbert.transformer.layer.4.attention.v_lin.bias
Frozen: distilbert.transformer.layer.4.attention.out_lin.weight
Frozen: distilbert.transformer.layer.4.attention.out_lin.bias
Frozen: distilbert.transformer.layer.4.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.4.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.4.ffn.lin1.weight
Frozen: distilbert.transformer.layer.4.ffn.lin1.bias
Frozen: distilbert.transformer.layer.4.ffn.lin2.weight
Frozen: distilbert.transformer.layer.4.ffn.lin2.bias
Frozen: distilbert.transformer.layer.4.output_layer_norm.weight
Frozen: distilbert.transformer.layer.4.output_layer_norm.bias
Frozen: distilbert.transformer.layer.5.attention.q_lin.weight
Frozen: distilbert.transformer.layer.5.attention.q_lin.bias
Frozen: distilbert.transformer.layer.5.attention.k_lin.weight
Frozen: distilbert.transformer.layer.5.attention.k_lin.bias
Frozen: distilbert.transformer.layer.5.attention.v_lin.weight
Frozen: distilbert.transformer.layer.5.attention.v_lin.bias
Frozen: distilbert.transformer.layer.5.attention.out_lin.weight
Frozen: distilbert.transformer.layer.5.attention.out_lin.bias
Frozen: distilbert.transformer.layer.5.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.5.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.5.ffn.lin1.weight
Frozen: distilbert.transformer.layer.5.ffn.lin1.bias
Frozen: distilbert.transformer.layer.5.ffn.lin2.weight
Frozen: distilbert.transformer.layer.5.ffn.lin2.bias
Frozen: distilbert.transformer.layer.5.output_layer_norm.weight
Frozen: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [42]:
training_args_Comprehensible_DistilBertLast3LayerFusion_model = TrainingArguments(

    output_dir                 = "Saved_models/Comprehensible_DistilBertLast3LayerFusion_config",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBertLast3LayerFusion_model_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBertLast3LayerFusion_model,
    args              = training_args_Comprehensible_DistilBertLast3LayerFusion_model,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
training_args_Comprehensible_DistilBertLast3LayerFusion_model

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Comprehensible_DBSC_FT_3_layers\runs\Jan30_08-47-33_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Comprehensible_DBSC_FT_3_layers,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [44]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBertLast3LayerFusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBertLast3LayerFusion_model_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:25:12.768002
[5112.768001599936 Seconds]
________________________________________

## Repetition_free

In [37]:
Repetition_free_DistilBertLast3LayerFusion_config = DistilBertConfig.from_pretrained(
                                                    "distilbert-base-multilingual-cased",
                                                    num_labels=2,
                                                    dropout=0.1,
                                                    attention_dropout=0.1,
                                                    seq_classif_dropout=0.1,
                                                )

Repetition_free_DistilBertLast3LayerFusion_model = DistilBertLast3LayerFusion.from_pretrained(
    "distilbert-base-multilingual-cased",
    config=Repetition_free_DistilBertLast3LayerFusion_config,
    ignore_mismatched_sizes=True  # important for custom head
)

Some weights of DistilBertLast3LayerFusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Repetition_free_DistilBertLast3LayerFusion_model) # See notes above on why ReLU activation does not show.

DistilBertLast3LayerFusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=4608, out_features=1024, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=1024, out_features=2, bias=True)
  )
)

Freeze all DestilBERT. We use only as Feature Extractor.

In [39]:
freeze_all_destilbert(Repetition_free_DistilBertLast3LayerFusion_model)

In [40]:
show_trainable_and_frozen(Repetition_free_DistilBertLast3LayerFusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Frozen: distilbert.transformer.layer.4.attention.q_lin.weight
Frozen: distilbert.transformer.layer.4.attention.q_lin.bias
Frozen: distilbert.transformer.layer.4.attention.k_lin.weight
Frozen: distilbert.transformer.layer.4.attention.k_lin.bias
Frozen: distilbert.transformer.layer.4.attention.v_lin.weight
Frozen: distilbert.transformer.layer.4.attention.v_lin.bias
Frozen: distilbert.transformer.layer.4.attention.out_lin.weight
Frozen: distilbert.transformer.layer.4.attention.out_lin.bias
Frozen: distilbert.transformer.layer.4.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.4.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.4.ffn.lin1.weight
Frozen: distilbert.transformer.layer.4.ffn.lin1.bias
Frozen: distilbert.transformer.layer.4.ffn.lin2.weight
Frozen: distilbert.transformer.layer.4.ffn.lin2.bias
Frozen: distilbert.transformer.layer.4.output_layer_norm.weight
Frozen: distilbert.transformer.layer.4.output_layer_norm.bias
Frozen: distilbert.transformer.layer.5.attention.q_lin.weight
Frozen: distilbert.transformer.layer.5.attention.q_lin.bias
Frozen: distilbert.transformer.layer.5.attention.k_lin.weight
Frozen: distilbert.transformer.layer.5.attention.k_lin.bias
Frozen: distilbert.transformer.layer.5.attention.v_lin.weight
Frozen: distilbert.transformer.layer.5.attention.v_lin.bias
Frozen: distilbert.transformer.layer.5.attention.out_lin.weight
Frozen: distilbert.transformer.layer.5.attention.out_lin.bias
Frozen: distilbert.transformer.layer.5.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.5.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.5.ffn.lin1.weight
Frozen: distilbert.transformer.layer.5.ffn.lin1.bias
Frozen: distilbert.transformer.layer.5.ffn.lin2.weight
Frozen: distilbert.transformer.layer.5.ffn.lin2.bias
Frozen: distilbert.transformer.layer.5.output_layer_norm.weight
Frozen: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [41]:
training_args_Repetition_free_DistilBertLast3LayerFusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_free_DistilBertLast3LayerFusion",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_free_DistilBertLast3LayerFusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_free_DistilBertLast3LayerFusion_model,
    args              = training_args_Repetition_free_DistilBertLast3LayerFusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Repetition_free_DistilBertLast3LayerFusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_free_DistilBertLast3LayerFusion\runs\Jan30_16-49-41_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_free_DistilBertLast3LayerFusion,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_free_DistilBertLast3LayerFusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_free_DistilBertLast3LayerFusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
0:59:56.396296
[3596.3962959998753 Seconds]
________________________________________

## Grammatical

In [38]:
Grammatical_DistilBertLast3LayerFusion_config = DistilBertConfig.from_pretrained(
                                                    "distilbert-base-multilingual-cased",
                                                    num_labels=2,
                                                    dropout=0.1,
                                                    attention_dropout=0.1,
                                                    seq_classif_dropout=0.1,
                                                )

Grammatical_DistilBertLast3LayerFusion_model = DistilBertLast3LayerFusion.from_pretrained(
    "distilbert-base-multilingual-cased",
    config=Grammatical_DistilBertLast3LayerFusion_config,
    ignore_mismatched_sizes=True  # important for custom head
)

Some weights of DistilBertLast3LayerFusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Grammatical_DistilBertLast3LayerFusion_model) # See notes above on why ReLU activation does not show.

DistilBertLast3LayerFusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=4608, out_features=1024, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=1024, out_features=2, bias=True)
  )
)

Freeze all DestilBERT. We use only as Feature Extractor.

In [40]:
freeze_all_destilbert(Grammatical_DistilBertLast3LayerFusion_model)

In [41]:
show_trainable_and_frozen(Grammatical_DistilBertLast3LayerFusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Frozen: distilbert.transformer.layer.4.attention.q_lin.weight
Frozen: distilbert.transformer.layer.4.attention.q_lin.bias
Frozen: distilbert.transformer.layer.4.attention.k_lin.weight
Frozen: distilbert.transformer.layer.4.attention.k_lin.bias
Frozen: distilbert.transformer.layer.4.attention.v_lin.weight
Frozen: distilbert.transformer.layer.4.attention.v_lin.bias
Frozen: distilbert.transformer.layer.4.attention.out_lin.weight
Frozen: distilbert.transformer.layer.4.attention.out_lin.bias
Frozen: distilbert.transformer.layer.4.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.4.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.4.ffn.lin1.weight
Frozen: distilbert.transformer.layer.4.ffn.lin1.bias
Frozen: distilbert.transformer.layer.4.ffn.lin2.weight
Frozen: distilbert.transformer.layer.4.ffn.lin2.bias
Frozen: distilbert.transformer.layer.4.output_layer_norm.weight
Frozen: distilbert.transformer.layer.4.output_layer_norm.bias
Frozen: distilbert.transformer.layer.5.attention.q_lin.weight
Frozen: distilbert.transformer.layer.5.attention.q_lin.bias
Frozen: distilbert.transformer.layer.5.attention.k_lin.weight
Frozen: distilbert.transformer.layer.5.attention.k_lin.bias
Frozen: distilbert.transformer.layer.5.attention.v_lin.weight
Frozen: distilbert.transformer.layer.5.attention.v_lin.bias
Frozen: distilbert.transformer.layer.5.attention.out_lin.weight
Frozen: distilbert.transformer.layer.5.attention.out_lin.bias
Frozen: distilbert.transformer.layer.5.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.5.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.5.ffn.lin1.weight
Frozen: distilbert.transformer.layer.5.ffn.lin1.bias
Frozen: distilbert.transformer.layer.5.ffn.lin2.weight
Frozen: distilbert.transformer.layer.5.ffn.lin2.bias
Frozen: distilbert.transformer.layer.5.output_layer_norm.weight
Frozen: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [42]:
training_args_Grammatical_DistilBertLast3LayerFusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_DistilBertLast3LayerFusion",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBertLast3LayerFusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBertLast3LayerFusion_model,
    args              = training_args_Grammatical_DistilBertLast3LayerFusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
training_args_Grammatical_DistilBertLast3LayerFusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_DistilBertLast3LayerFusion\runs\Jan30_18-09-37_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_DistilBertLast3LayerFusion,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [44]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBertLast3LayerFusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBertLast3LayerFusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
0:57:18.739074
[3438.7390743000433 Seconds]
________________________________________

# Sum Fusion (2 layers)

## Comprehensible

In [38]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [40]:
freeze_first_n_layers(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [41]:
show_trainable_and_frozen(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [42]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion\runs\Jan31_01-07-40_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [44]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
2:00:54.307252
[7254.307251500199 Seconds]
________________________________________

## Repetition

In [38]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [40]:
freeze_first_n_layers(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [41]:
show_trainable_and_frozen(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [42]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion\runs\Jan31_03-21-32_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [44]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:21:23.758586
[4883.7585862998385 Seconds]
________________________________________

## Grammatical

In [38]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [40]:
freeze_first_n_layers(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [41]:
show_trainable_and_frozen(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [42]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion\runs\Jan31_04-51-33_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [44]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:21:42.271721
[4902.271721499972 Seconds]
________________________________________

# Concat Fusion (2 layers)

## Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

In [38]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 4 layers

In [40]:
freeze_first_n_layers(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 4)

In [41]:
show_trainable_and_frozen(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [43]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [44]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion\runs\Jan31_06-33-17_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [45]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
2:01:38.080620
[7298.080620199908 Seconds]
________________________________________

## Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

In [38]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 4 layers

In [40]:
freeze_first_n_layers(Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 4)

In [41]:
show_trainable_and_frozen(Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [42]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion\runs\Jan31_09-07-15_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [44]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:28:56.401461
[5336.401460899971 Seconds]
________________________________________

## Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

In [38]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 4 layers

In [40]:
freeze_first_n_layers(Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 4)

In [41]:
show_trainable_and_frozen(Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [42]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion\runs\Jan31_12-09-47_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [44]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:27:35.204760
[5255.2047604 Seconds]
________________________________________

# Low Rank Adaption (LoRA)

## LoRA (Comprehensible)

In [37]:
Comprehensible_FT_for_LoRA = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-multilingual-cased",
    num_labels=2
)
#A warning is displayed because Head aimed for fine tuning has not yet weights.

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [38]:
from peft import LoraConfig, TaskType, get_peft_model

# Instantiate in same cell model for safety. A warning appears when we apply LoRA several times to a same object.

Comprehensible_FT_for_LoRA_config = LoraConfig(
    task_type = TaskType.SEQ_CLS,
    r = 8,
    lora_alpha = 32,
    lora_dropout = 0.05,
    # Last 3 layers: 3, 4, 5
    target_modules = r".*layer\.(3|4|5)\.attention\.(q_lin|k_lin|v_lin|out_lin)",
    bias="none",
)

Comprehensible_FT_LoRA_model = get_peft_model(Comprehensible_FT_for_LoRA, Comprehensible_FT_for_LoRA_config)
Comprehensible_FT_LoRA_model.print_trainable_parameters()

trainable params: 739,586 || all params: 136,065,796 || trainable%: 0.5436

Inspect architecture

In [39]:
print(Comprehensible_FT_LoRA_model) # See notes above on why ReLU activation does not show.

PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): DistilBertForSequenceClassification(
      (distilbert): DistilBertModel(
        (embeddings): Embeddings(
          (word_embeddings): Embedding(119547, 768, padding_idx=0)
          (position_embeddings): Embedding(512, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (transformer): Transformer(
          (layer): ModuleList(
            (0-2): 3 x TransformerBlock(
              (attention): DistilBertSdpaAttention(
                (dropout): Dropout(p=0.1, inplace=False)
                (q_lin): Linear(in_features=768, out_features=768, bias=True)
                (k_lin): Linear(in_features=768, out_features=768, bias=True)
                (v_lin): Linear(in_features=768, out_features=768, bias=True)
                (out_lin): Linear(in_features=768, out_features=768, bias=True)
              )
              (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (ffn): FFN(
                (dropout): Dropout(p=0.1, inplace=False)
                (lin1): Linear(in_features=768, out_features=3072, bias=True)
                (lin2): Linear(in_features=3072, out_features=768, bias=True)
                (activation): GELUActivation()
              )
              (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            )
            (3-5): 3 x TransformerBlock(
              (attention): DistilBertSdpaAttention(
                (dropout): Dropout(p=0.1, inplace=False)
                (q_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (k_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (v_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
              )
              (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (ffn): FFN(
                (dropout): Dropout(p=0.1, inplace=False)
                (lin1): Linear(in_features=768, out_features=3072, bias=True)
                (lin2): Linear(in_features=3072, out_features=768, bias=True)
                (activation): GELUActivation()
              )
              (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            )
          )
        )
      )
      (pre_classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=768, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=768, bias=True)
        )
      )
      (classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=2, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=2, bias=True)
        )
      )
      (dropout): Dropout(p=0.2, inplace=False)
    )
  )
)

See frozen base model

In [40]:
show_trainable_and_frozen(Comprehensible_FT_LoRA_model)

Frozen: base_model.model.distilbert.embeddings.word_embeddings.weight
Frozen: base_model.model.distilbert.embeddings.position_embeddings.weight
Frozen: base_model.model.distilbert.embeddings.LayerNorm.weight
Frozen: base_model.model.distilbert.embeddings.LayerNorm.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.3.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.3.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.3.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.3.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.3.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.3.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.3.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.3.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.3.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.4.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.4.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.4.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.4.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.5.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.5.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.5.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.5.output_layer_norm.bias
Frozen: base_model.model.pre_classifier.original_module.weight
Frozen: base_model.model.pre_classifier.original_module.bias
Trainable: base_model.model.pre_classifier.modules_to_save.default.weight
Trainable: base_model.model.pre_classifier.modules_to_save.default.bias
Frozen: base_model.model.classifier.original_module.weight
Frozen: base_model.model.classifier.original_module.bias
Trainable: base_model.model.classifier.modules_to_save.default.weight
Trainable: base_model.model.classifier.modules_to_save.default.bias

Train the model

In [41]:
training_args_Comprehensible_FT_LoRA_model = TrainingArguments(

    output_dir                 = "Saved_models/Comprehensible_FT_LoRA_model",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_FT_LoRA_model_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_FT_LoRA_model,
    args              = training_args_Comprehensible_FT_LoRA_model,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Comprehensible_FT_LoRA_model

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Comprehensible_FT_LoRA_model\runs\Jan31_14-28-29_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Comprehensible_FT_LoRA_model,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
import torch

# Force out-of-memory errors instead of spilling
#torch.cuda.set_per_process_memory_fraction(0.95, device=0)

# Disable memory growth that might cause spills
#os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:False'

# Check if you're spilling to CPU
#print(f"GPU Memory: {torch.cuda.memory_allocated(0)/1024**3:.2f} GB")


# If max_memory > 4GB, you're likely spilling or will crash

In [44]:
import torch

# Get device name
print(f"Device name: {torch.cuda.get_device_name(0)}")

# Current memory usage
allocated = torch.cuda.memory_allocated(0) / 1024**3
reserved = torch.cuda.memory_reserved(0) / 1024**3
total = torch.cuda.get_device_properties(0).total_memory / 1024**3

print(f"Allocated: {allocated:.2f} GB")
print(f"Reserved: {reserved:.2f} GB")
print(f"Total: {total:.2f} GB")
print(f"Free: {total - reserved:.2f} GB")
print(f"Max GPU Memory: {torch.cuda.max_memory_allocated(0)/1024**3:.2f} GB") # peak usage

Device name: NVIDIA GeForce GTX 1650
Allocated: 0.51 GB
Reserved: 0.54 GB
Total: 4.00 GB
Free: 3.46 GB
Max GPU Memory: 0.51 GB

In [45]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_FT_LoRA_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_FT_LoRA_model_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
3:50:01.111652
[13801.111652100002 Seconds]
________________________________________

## LoRA (Repetition)

In [37]:
Repetition_FT_for_LoRA = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-multilingual-cased",
    num_labels=2
)
#A warning is displayed because Head aimed for fine tuning has not yet weights.

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [38]:
from peft import LoraConfig, TaskType, get_peft_model

# Instantiate in same cell model for safety. A warning appears when we apply LoRA several times to a same object.

Repetition_FT_for_LoRA_config = LoraConfig(
    task_type = TaskType.SEQ_CLS,
    r = 8,
    lora_alpha = 32,
    lora_dropout = 0.05,
    # Last 3 layers: 3, 4, 5
    target_modules = r".*layer\.(3|4|5)\.attention\.(q_lin|k_lin|v_lin|out_lin)",
    bias="none",
)

Repetition_FT_LoRA_model = get_peft_model(Repetition_FT_for_LoRA, Repetition_FT_for_LoRA_config)
Repetition_FT_LoRA_model.print_trainable_parameters()

trainable params: 739,586 || all params: 136,065,796 || trainable%: 0.5436

Inspect architecture

In [39]:
print(Repetition_FT_LoRA_model) # See notes above on why ReLU activation does not show.

PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): DistilBertForSequenceClassification(
      (distilbert): DistilBertModel(
        (embeddings): Embeddings(
          (word_embeddings): Embedding(119547, 768, padding_idx=0)
          (position_embeddings): Embedding(512, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (transformer): Transformer(
          (layer): ModuleList(
            (0-2): 3 x TransformerBlock(
              (attention): DistilBertSdpaAttention(
                (dropout): Dropout(p=0.1, inplace=False)
                (q_lin): Linear(in_features=768, out_features=768, bias=True)
                (k_lin): Linear(in_features=768, out_features=768, bias=True)
                (v_lin): Linear(in_features=768, out_features=768, bias=True)
                (out_lin): Linear(in_features=768, out_features=768, bias=True)
              )
              (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (ffn): FFN(
                (dropout): Dropout(p=0.1, inplace=False)
                (lin1): Linear(in_features=768, out_features=3072, bias=True)
                (lin2): Linear(in_features=3072, out_features=768, bias=True)
                (activation): GELUActivation()
              )
              (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            )
            (3-5): 3 x TransformerBlock(
              (attention): DistilBertSdpaAttention(
                (dropout): Dropout(p=0.1, inplace=False)
                (q_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (k_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (v_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
              )
              (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (ffn): FFN(
                (dropout): Dropout(p=0.1, inplace=False)
                (lin1): Linear(in_features=768, out_features=3072, bias=True)
                (lin2): Linear(in_features=3072, out_features=768, bias=True)
                (activation): GELUActivation()
              )
              (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            )
          )
        )
      )
      (pre_classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=768, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=768, bias=True)
        )
      )
      (classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=2, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=2, bias=True)
        )
      )
      (dropout): Dropout(p=0.2, inplace=False)
    )
  )
)

See frozen base model

In [40]:
show_trainable_and_frozen(Repetition_FT_LoRA_model)

Frozen: base_model.model.distilbert.embeddings.word_embeddings.weight
Frozen: base_model.model.distilbert.embeddings.position_embeddings.weight
Frozen: base_model.model.distilbert.embeddings.LayerNorm.weight
Frozen: base_model.model.distilbert.embeddings.LayerNorm.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.3.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.3.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.3.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.3.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.3.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.3.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.3.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.3.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.3.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.4.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.4.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.4.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.4.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.5.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.5.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.5.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.5.output_layer_norm.bias
Frozen: base_model.model.pre_classifier.original_module.weight
Frozen: base_model.model.pre_classifier.original_module.bias
Trainable: base_model.model.pre_classifier.modules_to_save.default.weight
Trainable: base_model.model.pre_classifier.modules_to_save.default.bias
Frozen: base_model.model.classifier.original_module.weight
Frozen: base_model.model.classifier.original_module.bias
Trainable: base_model.model.classifier.modules_to_save.default.weight
Trainable: base_model.model.classifier.modules_to_save.default.bias

Train the model

In [41]:
training_args_Repetition_FT_LoRA_model = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_FT_LoRA_model",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_FT_LoRA_model_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_FT_LoRA_model,
    args              = training_args_Repetition_FT_LoRA_model,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Repetition_FT_LoRA_model

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_FT_LoRA_model\runs\Feb01_00-39-42_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_FT_LoRA_model,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
import torch

# Force out-of-memory errors instead of spilling
#torch.cuda.set_per_process_memory_fraction(0.95, device=0)

# Disable memory growth that might cause spills
#os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:False'

# Check if you're spilling to CPU
#print(f"GPU Memory: {torch.cuda.memory_allocated(0)/1024**3:.2f} GB")


# If max_memory > 4GB, you're likely spilling or will crash

In [44]:
import torch

# Get device name
print(f"Device name: {torch.cuda.get_device_name(0)}")

# Current memory usage
allocated = torch.cuda.memory_allocated(0) / 1024**3
reserved = torch.cuda.memory_reserved(0) / 1024**3
total = torch.cuda.get_device_properties(0).total_memory / 1024**3

print(f"Allocated: {allocated:.2f} GB")
print(f"Reserved: {reserved:.2f} GB")
print(f"Total: {total:.2f} GB")
print(f"Free: {total - reserved:.2f} GB")
print(f"Max GPU Memory: {torch.cuda.max_memory_allocated(0)/1024**3:.2f} GB") # peak usage

Device name: NVIDIA GeForce GTX 1650
Allocated: 0.51 GB
Reserved: 0.54 GB
Total: 4.00 GB
Free: 3.46 GB
Max GPU Memory: 0.51 GB

In [45]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_FT_LoRA_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_FT_LoRA_model_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
3:28:46.480848
[12526.4808481 Seconds]
________________________________________

## LoRA (Grammatical)

In [37]:
Grammatical_FT_for_LoRA = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-multilingual-cased",
    num_labels=2
)
#A warning is displayed because Head aimed for fine tuning has not yet weights.

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [39]:
from peft import LoraConfig, TaskType, get_peft_model

# Instantiate in same cell model for safety. A warning appears when we apply LoRA several times to a same object.

Grammatical_FT_for_LoRA_config = LoraConfig(
    task_type = TaskType.SEQ_CLS,
    r = 8,
    lora_alpha = 32,
    lora_dropout = 0.05,
    # Last 3 layers: 3, 4, 5
    target_modules = r".*layer\.(3|4|5)\.attention\.(q_lin|k_lin|v_lin|out_lin)",
    bias="none",
)

Grammatical_FT_LoRA_model = get_peft_model(Grammatical_FT_for_LoRA, Grammatical_FT_for_LoRA_config)
Grammatical_FT_LoRA_model.print_trainable_parameters()

trainable params: 739,586 || all params: 136,065,796 || trainable%: 0.5436

Inspect architecture

In [40]:
print(Grammatical_FT_LoRA_model) # See notes above on why ReLU activation does not show.

PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): DistilBertForSequenceClassification(
      (distilbert): DistilBertModel(
        (embeddings): Embeddings(
          (word_embeddings): Embedding(119547, 768, padding_idx=0)
          (position_embeddings): Embedding(512, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (transformer): Transformer(
          (layer): ModuleList(
            (0-2): 3 x TransformerBlock(
              (attention): DistilBertSdpaAttention(
                (dropout): Dropout(p=0.1, inplace=False)
                (q_lin): Linear(in_features=768, out_features=768, bias=True)
                (k_lin): Linear(in_features=768, out_features=768, bias=True)
                (v_lin): Linear(in_features=768, out_features=768, bias=True)
                (out_lin): Linear(in_features=768, out_features=768, bias=True)
              )
              (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (ffn): FFN(
                (dropout): Dropout(p=0.1, inplace=False)
                (lin1): Linear(in_features=768, out_features=3072, bias=True)
                (lin2): Linear(in_features=3072, out_features=768, bias=True)
                (activation): GELUActivation()
              )
              (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            )
            (3-5): 3 x TransformerBlock(
              (attention): DistilBertSdpaAttention(
                (dropout): Dropout(p=0.1, inplace=False)
                (q_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (k_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (v_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
              )
              (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (ffn): FFN(
                (dropout): Dropout(p=0.1, inplace=False)
                (lin1): Linear(in_features=768, out_features=3072, bias=True)
                (lin2): Linear(in_features=3072, out_features=768, bias=True)
                (activation): GELUActivation()
              )
              (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            )
          )
        )
      )
      (pre_classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=768, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=768, bias=True)
        )
      )
      (classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=2, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=2, bias=True)
        )
      )
      (dropout): Dropout(p=0.2, inplace=False)
    )
  )
)

See frozen base model

In [41]:
show_trainable_and_frozen(Grammatical_FT_LoRA_model)

Frozen: base_model.model.distilbert.embeddings.word_embeddings.weight
Frozen: base_model.model.distilbert.embeddings.position_embeddings.weight
Frozen: base_model.model.distilbert.embeddings.LayerNorm.weight
Frozen: base_model.model.distilbert.embeddings.LayerNorm.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.3.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.3.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.3.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.3.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.3.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.3.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.3.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.3.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.3.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.4.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.4.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.4.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.4.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.5.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.5.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.5.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.5.output_layer_norm.bias
Frozen: base_model.model.pre_classifier.original_module.weight
Frozen: base_model.model.pre_classifier.original_module.bias
Trainable: base_model.model.pre_classifier.modules_to_save.default.weight
Trainable: base_model.model.pre_classifier.modules_to_save.default.bias
Frozen: base_model.model.classifier.original_module.weight
Frozen: base_model.model.classifier.original_module.bias
Trainable: base_model.model.classifier.modules_to_save.default.weight
Trainable: base_model.model.classifier.modules_to_save.default.bias

Train the model

In [46]:
training_args_Grammatical_FT_LoRA = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_FT_LoRA_model",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_FT_LoRA_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_FT_LoRA_model,
    args              = training_args_Grammatical_FT_LoRA,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [47]:
training_args_Grammatical_FT_LoRA

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_FT_LoRA_model\runs\Feb01_04-35-13_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_FT_LoRA_model,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [48]:
import torch

# Force out-of-memory errors instead of spilling
#torch.cuda.set_per_process_memory_fraction(0.95, device=0)

# Disable memory growth that might cause spills
#os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:False'

# Check if you're spilling to CPU
#print(f"GPU Memory: {torch.cuda.memory_allocated(0)/1024**3:.2f} GB")


# If max_memory > 4GB, you're likely spilling or will crash

In [49]:
import torch

# Get device name
print(f"Device name: {torch.cuda.get_device_name(0)}")

# Current memory usage
allocated = torch.cuda.memory_allocated(0) / 1024**3
reserved = torch.cuda.memory_reserved(0) / 1024**3
total = torch.cuda.get_device_properties(0).total_memory / 1024**3

print(f"Allocated: {allocated:.2f} GB")
print(f"Reserved: {reserved:.2f} GB")
print(f"Total: {total:.2f} GB")
print(f"Free: {total - reserved:.2f} GB")
print(f"Max GPU Memory: {torch.cuda.max_memory_allocated(0)/1024**3:.2f} GB") # peak usage

Device name: NVIDIA GeForce GTX 1650
Allocated: 0.51 GB
Reserved: 0.54 GB
Total: 4.00 GB
Free: 3.46 GB
Max GPU Memory: 0.51 GB

In [50]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_FT_LoRA_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_FT_LoRA_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
3:25:46.534889
[12346.534888899994 Seconds]
________________________________________

# Fusions (3 layers)

## Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion (3 Layers)

In [38]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 3 layers

In [40]:
freeze_first_n_layers(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 3)

In [41]:
show_trainable_and_frozen(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Trainable: distilbert.transformer.layer.3.attention.q_lin.weight
Trainable: distilbert.transformer.layer.3.attention.q_lin.bias
Trainable: distilbert.transformer.layer.3.attention.k_lin.weight
Trainable: distilbert.transformer.layer.3.attention.k_lin.bias
Trainable: distilbert.transformer.layer.3.attention.v_lin.weight
Trainable: distilbert.transformer.layer.3.attention.v_lin.bias
Trainable: distilbert.transformer.layer.3.attention.out_lin.weight
Trainable: distilbert.transformer.layer.3.attention.out_lin.bias
Trainable: distilbert.transformer.layer.3.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.3.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.3.ffn.lin1.weight
Trainable: distilbert.transformer.layer.3.ffn.lin1.bias
Trainable: distilbert.transformer.layer.3.ffn.lin2.weight
Trainable: distilbert.transformer.layer.3.ffn.lin2.bias
Trainable: distilbert.transformer.layer.3.output_layer_norm.weight
Trainable: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [42]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_3_layers",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_3_layers\runs\Feb01_15-01-49_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_3_layers,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [44]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
6:28:20.450231
[23300.450230899994 Seconds]
________________________________________

## Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion (3 layers)

In [38]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 3 layers

In [40]:
freeze_first_n_layers(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 3)

In [41]:
show_trainable_and_frozen(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Trainable: distilbert.transformer.layer.3.attention.q_lin.weight
Trainable: distilbert.transformer.layer.3.attention.q_lin.bias
Trainable: distilbert.transformer.layer.3.attention.k_lin.weight
Trainable: distilbert.transformer.layer.3.attention.k_lin.bias
Trainable: distilbert.transformer.layer.3.attention.v_lin.weight
Trainable: distilbert.transformer.layer.3.attention.v_lin.bias
Trainable: distilbert.transformer.layer.3.attention.out_lin.weight
Trainable: distilbert.transformer.layer.3.attention.out_lin.bias
Trainable: distilbert.transformer.layer.3.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.3.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.3.ffn.lin1.weight
Trainable: distilbert.transformer.layer.3.ffn.lin1.bias
Trainable: distilbert.transformer.layer.3.ffn.lin2.weight
Trainable: distilbert.transformer.layer.3.ffn.lin2.bias
Trainable: distilbert.transformer.layer.3.output_layer_norm.weight
Trainable: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [42]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_3_layers",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_3_layers\runs\Feb01_21-39-44_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_3_layers,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [44]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
8:23:53.232683
[30233.232682700007 Seconds]
________________________________________

## Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion (3 layers)

In [38]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [40]:
freeze_first_n_layers(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 3)

In [41]:
show_trainable_and_frozen(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Trainable: distilbert.transformer.layer.3.attention.q_lin.weight
Trainable: distilbert.transformer.layer.3.attention.q_lin.bias
Trainable: distilbert.transformer.layer.3.attention.k_lin.weight
Trainable: distilbert.transformer.layer.3.attention.k_lin.bias
Trainable: distilbert.transformer.layer.3.attention.v_lin.weight
Trainable: distilbert.transformer.layer.3.attention.v_lin.bias
Trainable: distilbert.transformer.layer.3.attention.out_lin.weight
Trainable: distilbert.transformer.layer.3.attention.out_lin.bias
Trainable: distilbert.transformer.layer.3.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.3.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.3.ffn.lin1.weight
Trainable: distilbert.transformer.layer.3.ffn.lin1.bias
Trainable: distilbert.transformer.layer.3.ffn.lin2.weight
Trainable: distilbert.transformer.layer.3.ffn.lin2.bias
Trainable: distilbert.transformer.layer.3.output_layer_norm.weight
Trainable: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [43]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_3_layers",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [44]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_3_layers\runs\Feb02_09-52-31_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_3_layers,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [45]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
6:46:37.109870
[24397.109870199987 Seconds]
________________________________________

## Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion (3 layers)

In [38]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 3 layers

In [40]:
freeze_first_n_layers(Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 3)

In [41]:
show_trainable_and_frozen(Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Trainable: distilbert.transformer.layer.3.attention.q_lin.weight
Trainable: distilbert.transformer.layer.3.attention.q_lin.bias
Trainable: distilbert.transformer.layer.3.attention.k_lin.weight
Trainable: distilbert.transformer.layer.3.attention.k_lin.bias
Trainable: distilbert.transformer.layer.3.attention.v_lin.weight
Trainable: distilbert.transformer.layer.3.attention.v_lin.bias
Trainable: distilbert.transformer.layer.3.attention.out_lin.weight
Trainable: distilbert.transformer.layer.3.attention.out_lin.bias
Trainable: distilbert.transformer.layer.3.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.3.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.3.ffn.lin1.weight
Trainable: distilbert.transformer.layer.3.ffn.lin1.bias
Trainable: distilbert.transformer.layer.3.ffn.lin2.weight
Trainable: distilbert.transformer.layer.3.ffn.lin2.bias
Trainable: distilbert.transformer.layer.3.output_layer_norm.weight
Trainable: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [42]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_3_layers",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_3_layers\runs\Feb02_17-09-04_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_3_layers,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [44]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
5:14:00.965649
[18840.96564909999 Seconds]
________________________________________

## Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion (3 layers)

In [38]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [40]:
freeze_first_n_layers(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 3)

In [41]:
show_trainable_and_frozen(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Trainable: distilbert.transformer.layer.3.attention.q_lin.weight
Trainable: distilbert.transformer.layer.3.attention.q_lin.bias
Trainable: distilbert.transformer.layer.3.attention.k_lin.weight
Trainable: distilbert.transformer.layer.3.attention.k_lin.bias
Trainable: distilbert.transformer.layer.3.attention.v_lin.weight
Trainable: distilbert.transformer.layer.3.attention.v_lin.bias
Trainable: distilbert.transformer.layer.3.attention.out_lin.weight
Trainable: distilbert.transformer.layer.3.attention.out_lin.bias
Trainable: distilbert.transformer.layer.3.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.3.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.3.ffn.lin1.weight
Trainable: distilbert.transformer.layer.3.ffn.lin1.bias
Trainable: distilbert.transformer.layer.3.ffn.lin2.weight
Trainable: distilbert.transformer.layer.3.ffn.lin2.bias
Trainable: distilbert.transformer.layer.3.output_layer_norm.weight
Trainable: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [42]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_3_layers",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_3_layers\runs\Feb03_01-35-45_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_3_layers,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [44]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
5:19:18.912199
[19158.912198799982 Seconds]
________________________________________

## Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion (3 Layers)

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 3)

In [40]:
show_trainable_and_frozen(Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Trainable: distilbert.transformer.layer.3.attention.q_lin.weight
Trainable: distilbert.transformer.layer.3.attention.q_lin.bias
Trainable: distilbert.transformer.layer.3.attention.k_lin.weight
Trainable: distilbert.transformer.layer.3.attention.k_lin.bias
Trainable: distilbert.transformer.layer.3.attention.v_lin.weight
Trainable: distilbert.transformer.layer.3.attention.v_lin.bias
Trainable: distilbert.transformer.layer.3.attention.out_lin.weight
Trainable: distilbert.transformer.layer.3.attention.out_lin.bias
Trainable: distilbert.transformer.layer.3.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.3.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.3.ffn.lin1.weight
Trainable: distilbert.transformer.layer.3.ffn.lin1.bias
Trainable: distilbert.transformer.layer.3.ffn.lin2.weight
Trainable: distilbert.transformer.layer.3.ffn.lin2.bias
Trainable: distilbert.transformer.layer.3.output_layer_norm.weight
Trainable: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [41]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_3_layers",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_3_layers\runs\Feb03_07-23-51_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_3_layers,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
5:20:52.385097
[19252.38509669999 Seconds]
________________________________________

# 2. Feature Extraction and LoRA (more epochs)

# Low Rank Adaption (LoRA)

# Comprehensible_FT_for_LoRA

In [37]:
Comprehensible_FT_for_LoRA = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-multilingual-cased",
    num_labels=2
)
#A warning is displayed because Head aimed for fine tuning has not yet weights.

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [38]:
from peft import LoraConfig, TaskType, get_peft_model

# Instantiate in same cell model for safety. A warning appears when we apply LoRA several times to a same object.

Comprehensible_FT_for_LoRA_config = LoraConfig(
    task_type = TaskType.SEQ_CLS,
    r = 8,
    lora_alpha = 32,
    lora_dropout = 0.05,
    # Last 2 layers:  4, 5
    target_modules = r".*layer\.(4|5)\.attention\.(q_lin|k_lin|v_lin|out_lin)",
    bias="none",
)

Comprehensible_FT_LoRA_model = get_peft_model(Comprehensible_FT_for_LoRA, Comprehensible_FT_for_LoRA_config)
Comprehensible_FT_LoRA_model.print_trainable_parameters()

trainable params: 690,434 || all params: 136,016,644 || trainable%: 0.5076

Inspect architecture

In [39]:
print(Comprehensible_FT_LoRA_model) # See notes above on why ReLU activation does not show.

PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): DistilBertForSequenceClassification(
      (distilbert): DistilBertModel(
        (embeddings): Embeddings(
          (word_embeddings): Embedding(119547, 768, padding_idx=0)
          (position_embeddings): Embedding(512, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (transformer): Transformer(
          (layer): ModuleList(
            (0-3): 4 x TransformerBlock(
              (attention): DistilBertSdpaAttention(
                (dropout): Dropout(p=0.1, inplace=False)
                (q_lin): Linear(in_features=768, out_features=768, bias=True)
                (k_lin): Linear(in_features=768, out_features=768, bias=True)
                (v_lin): Linear(in_features=768, out_features=768, bias=True)
                (out_lin): Linear(in_features=768, out_features=768, bias=True)
              )
              (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (ffn): FFN(
                (dropout): Dropout(p=0.1, inplace=False)
                (lin1): Linear(in_features=768, out_features=3072, bias=True)
                (lin2): Linear(in_features=3072, out_features=768, bias=True)
                (activation): GELUActivation()
              )
              (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            )
            (4-5): 2 x TransformerBlock(
              (attention): DistilBertSdpaAttention(
                (dropout): Dropout(p=0.1, inplace=False)
                (q_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (k_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (v_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
              )
              (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (ffn): FFN(
                (dropout): Dropout(p=0.1, inplace=False)
                (lin1): Linear(in_features=768, out_features=3072, bias=True)
                (lin2): Linear(in_features=3072, out_features=768, bias=True)
                (activation): GELUActivation()
              )
              (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            )
          )
        )
      )
      (pre_classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=768, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=768, bias=True)
        )
      )
      (classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=2, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=2, bias=True)
        )
      )
      (dropout): Dropout(p=0.2, inplace=False)
    )
  )
)

See frozen base model

In [40]:
show_trainable_and_frozen(Comprehensible_FT_LoRA_model)

Frozen: base_model.model.distilbert.embeddings.word_embeddings.weight
Frozen: base_model.model.distilbert.embeddings.position_embeddings.weight
Frozen: base_model.model.distilbert.embeddings.LayerNorm.weight
Frozen: base_model.model.distilbert.embeddings.LayerNorm.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.3.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.4.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.4.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.4.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.4.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.5.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.5.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.5.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.5.output_layer_norm.bias
Frozen: base_model.model.pre_classifier.original_module.weight
Frozen: base_model.model.pre_classifier.original_module.bias
Trainable: base_model.model.pre_classifier.modules_to_save.default.weight
Trainable: base_model.model.pre_classifier.modules_to_save.default.bias
Frozen: base_model.model.classifier.original_module.weight
Frozen: base_model.model.classifier.original_module.bias
Trainable: base_model.model.classifier.modules_to_save.default.weight
Trainable: base_model.model.classifier.modules_to_save.default.bias

Train the model

In [41]:
training_args_Comprehensible_FT_LoRA_model = TrainingArguments(

    output_dir                 = "Saved_models/Comprehensible_FT_LoRA_model_3E_4_2_LAYERS",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 3e-4,
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 6,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_FT_LoRA_model_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_FT_LoRA_model,
    args              = training_args_Comprehensible_FT_LoRA_model,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Comprehensible_FT_LoRA_model

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0003,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Comprehensible_FT_LoRA_model_3E_4_2_LAYERS\runs\Feb09_06-48-49_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=6,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Comprehensible_FT_LoRA_model_3E_4_2_LAYERS,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
import torch

# Force out-of-memory errors instead of spilling
#torch.cuda.set_per_process_memory_fraction(0.95, device=0)

# Disable memory growth that might cause spills
#os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:False'

# Check if you're spilling to CPU
#print(f"GPU Memory: {torch.cuda.memory_allocated(0)/1024**3:.2f} GB")


# If max_memory > 4GB, you're likely spilling or will crash

In [44]:
import torch

# Get device name
print(f"Device name: {torch.cuda.get_device_name(0)}")

# Current memory usage
allocated = torch.cuda.memory_allocated(0) / 1024**3
reserved = torch.cuda.memory_reserved(0) / 1024**3
total = torch.cuda.get_device_properties(0).total_memory / 1024**3

print(f"Allocated: {allocated:.2f} GB")
print(f"Reserved: {reserved:.2f} GB")
print(f"Total: {total:.2f} GB")
print(f"Free: {total - reserved:.2f} GB")
print(f"Max GPU Memory: {torch.cuda.max_memory_allocated(0)/1024**3:.2f} GB") # peak usage

Device name: NVIDIA GeForce GTX 1650
Allocated: 0.51 GB
Reserved: 0.54 GB
Total: 4.00 GB
Free: 3.46 GB
Max GPU Memory: 0.51 GB

In [45]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_FT_LoRA_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_FT_LoRA_model_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
4:56:54.754154
[17814.754153999966 Seconds]
________________________________________

# Repetition_FT_for_LoRA

In [39]:
Repetition_FT_for_LoRA = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-multilingual-cased",
    num_labels=2
)
#A warning is displayed because Head aimed for fine tuning has not yet weights.

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [40]:
from peft import LoraConfig, TaskType, get_peft_model

# Instantiate in same cell model for safety. A warning appears when we apply LoRA several times to a same object.

Repetition_FT_for_LoRA_config = LoraConfig(
    task_type = TaskType.SEQ_CLS,
    r = 8,
    lora_alpha = 32,
    lora_dropout = 0.05,
    # Last 2 layers: 4, 5
    target_modules = r".*layer\.(4|5)\.attention\.(q_lin|k_lin|v_lin|out_lin)",
    bias="none",
)

Repetition_FT_LoRA_model = get_peft_model(Repetition_FT_for_LoRA, Repetition_FT_for_LoRA_config)
Repetition_FT_LoRA_model.print_trainable_parameters()

trainable params: 690,434 || all params: 136,016,644 || trainable%: 0.5076

Inspect architecture

In [41]:
print(Repetition_FT_LoRA_model) # See notes above on why ReLU activation does not show.

PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): DistilBertForSequenceClassification(
      (distilbert): DistilBertModel(
        (embeddings): Embeddings(
          (word_embeddings): Embedding(119547, 768, padding_idx=0)
          (position_embeddings): Embedding(512, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (transformer): Transformer(
          (layer): ModuleList(
            (0-3): 4 x TransformerBlock(
              (attention): DistilBertSdpaAttention(
                (dropout): Dropout(p=0.1, inplace=False)
                (q_lin): Linear(in_features=768, out_features=768, bias=True)
                (k_lin): Linear(in_features=768, out_features=768, bias=True)
                (v_lin): Linear(in_features=768, out_features=768, bias=True)
                (out_lin): Linear(in_features=768, out_features=768, bias=True)
              )
              (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (ffn): FFN(
                (dropout): Dropout(p=0.1, inplace=False)
                (lin1): Linear(in_features=768, out_features=3072, bias=True)
                (lin2): Linear(in_features=3072, out_features=768, bias=True)
                (activation): GELUActivation()
              )
              (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            )
            (4-5): 2 x TransformerBlock(
              (attention): DistilBertSdpaAttention(
                (dropout): Dropout(p=0.1, inplace=False)
                (q_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (k_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (v_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
              )
              (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (ffn): FFN(
                (dropout): Dropout(p=0.1, inplace=False)
                (lin1): Linear(in_features=768, out_features=3072, bias=True)
                (lin2): Linear(in_features=3072, out_features=768, bias=True)
                (activation): GELUActivation()
              )
              (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            )
          )
        )
      )
      (pre_classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=768, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=768, bias=True)
        )
      )
      (classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=2, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=2, bias=True)
        )
      )
      (dropout): Dropout(p=0.2, inplace=False)
    )
  )
)

See frozen base model

In [42]:
show_trainable_and_frozen(Repetition_FT_LoRA_model)

Frozen: base_model.model.distilbert.embeddings.word_embeddings.weight
Frozen: base_model.model.distilbert.embeddings.position_embeddings.weight
Frozen: base_model.model.distilbert.embeddings.LayerNorm.weight
Frozen: base_model.model.distilbert.embeddings.LayerNorm.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.3.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.4.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.4.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.4.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.4.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.5.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.5.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.5.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.5.output_layer_norm.bias
Frozen: base_model.model.pre_classifier.original_module.weight
Frozen: base_model.model.pre_classifier.original_module.bias
Trainable: base_model.model.pre_classifier.modules_to_save.default.weight
Trainable: base_model.model.pre_classifier.modules_to_save.default.bias
Frozen: base_model.model.classifier.original_module.weight
Frozen: base_model.model.classifier.original_module.bias
Trainable: base_model.model.classifier.modules_to_save.default.weight
Trainable: base_model.model.classifier.modules_to_save.default.bias

Train the model

In [44]:
training_args_Repetition_FT_LoRA_model = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_FT_LoRA_model_3E_4_2_layers",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 3e-4,
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 6,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_FT_LoRA_model_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_FT_LoRA_model,
    args              = training_args_Repetition_FT_LoRA_model,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [45]:
training_args_Repetition_FT_LoRA_model

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0003,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_FT_LoRA_model_3E_4_2_layers\runs\Feb09_17-42-49_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=6,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_FT_LoRA_model_3E_4_2_layers,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [46]:
import torch

# Force out-of-memory errors instead of spilling
#torch.cuda.set_per_process_memory_fraction(0.95, device=0)

# Disable memory growth that might cause spills
#os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:False'

# Check if you're spilling to CPU
#print(f"GPU Memory: {torch.cuda.memory_allocated(0)/1024**3:.2f} GB")


# If max_memory > 4GB, you're likely spilling or will crash

In [47]:
import torch

# Get device name
print(f"Device name: {torch.cuda.get_device_name(0)}")

# Current memory usage
allocated = torch.cuda.memory_allocated(0) / 1024**3
reserved = torch.cuda.memory_reserved(0) / 1024**3
total = torch.cuda.get_device_properties(0).total_memory / 1024**3

print(f"Allocated: {allocated:.2f} GB")
print(f"Reserved: {reserved:.2f} GB")
print(f"Total: {total:.2f} GB")
print(f"Free: {total - reserved:.2f} GB")
print(f"Max GPU Memory: {torch.cuda.max_memory_allocated(0)/1024**3:.2f} GB") # peak usage

Device name: NVIDIA GeForce GTX 1650
Allocated: 0.51 GB
Reserved: 0.54 GB
Total: 4.00 GB
Free: 3.46 GB
Max GPU Memory: 0.51 GB

Last epoch got saved but not displayed. Best ROC at 4

In [ ]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_FT_LoRA_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_FT_LoRA_model_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [42]:
compute_evaluation_metrics(X_data=tokenized_repetition_validation["text"],
                           y_true_labels=tokenized_repetition_validation["labels"],
                               model_for_inference = Repetition_FT_LoRA_reloaded,
                               input_text_tokenizer=tokenizer,
                               data_loader_batch_size = 32)

{'Accuracy': 0.9465420560747664,
 'Precision': 0.9824967452625488,
 'Sensitivity (Recall, TPR)': 0.9566197183098591,
 'Specificity (TNR)': np.float64(0.8691891891891892),
 "Youden's J statistic": np.float64(0.8258089074990482),
 'ROC AUC': 0.9650257327750287,
 'Pearson correlation': np.float64(0.793074941364947),
 'F1': 0.9693855705416399}

# Grammatical_FT_for_LoRA

In [37]:
Grammatical_FT_for_LoRA = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-multilingual-cased",
    num_labels=2
)
#A warning is displayed because Head aimed for fine tuning has not yet weights.

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [38]:
from peft import LoraConfig, TaskType, get_peft_model

# Instantiate in same cell model for safety. A warning appears when we apply LoRA several times to a same object.

Grammatical_FT_for_LoRA_config = LoraConfig(
    task_type = TaskType.SEQ_CLS,
    r = 8,
    lora_alpha = 32,
    lora_dropout = 0.05,
    # Last 2 layers:  4, 5
    target_modules = r".*layer\.(4|5)\.attention\.(q_lin|k_lin|v_lin|out_lin)",
    bias="none",
)

Grammatical_FT_LoRA_model = get_peft_model(Grammatical_FT_for_LoRA, Grammatical_FT_for_LoRA_config)
Grammatical_FT_LoRA_model.print_trainable_parameters()

trainable params: 690,434 || all params: 136,016,644 || trainable%: 0.5076

Inspect architecture

In [39]:
print(Grammatical_FT_LoRA_model) # See notes above on why ReLU activation does not show.

PeftModelForSequenceClassification(
  (base_model): LoraModel(
    (model): DistilBertForSequenceClassification(
      (distilbert): DistilBertModel(
        (embeddings): Embeddings(
          (word_embeddings): Embedding(119547, 768, padding_idx=0)
          (position_embeddings): Embedding(512, 768)
          (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
        (transformer): Transformer(
          (layer): ModuleList(
            (0-3): 4 x TransformerBlock(
              (attention): DistilBertSdpaAttention(
                (dropout): Dropout(p=0.1, inplace=False)
                (q_lin): Linear(in_features=768, out_features=768, bias=True)
                (k_lin): Linear(in_features=768, out_features=768, bias=True)
                (v_lin): Linear(in_features=768, out_features=768, bias=True)
                (out_lin): Linear(in_features=768, out_features=768, bias=True)
              )
              (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (ffn): FFN(
                (dropout): Dropout(p=0.1, inplace=False)
                (lin1): Linear(in_features=768, out_features=3072, bias=True)
                (lin2): Linear(in_features=3072, out_features=768, bias=True)
                (activation): GELUActivation()
              )
              (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            )
            (4-5): 2 x TransformerBlock(
              (attention): DistilBertSdpaAttention(
                (dropout): Dropout(p=0.1, inplace=False)
                (q_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (k_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (v_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
                (out_lin): lora.Linear(
                  (base_layer): Linear(in_features=768, out_features=768, bias=True)
                  (lora_dropout): ModuleDict(
                    (default): Dropout(p=0.05, inplace=False)
                  )
                  (lora_A): ModuleDict(
                    (default): Linear(in_features=768, out_features=8, bias=False)
                  )
                  (lora_B): ModuleDict(
                    (default): Linear(in_features=8, out_features=768, bias=False)
                  )
                  (lora_embedding_A): ParameterDict()
                  (lora_embedding_B): ParameterDict()
                  (lora_magnitude_vector): ModuleDict()
                )
              )
              (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (ffn): FFN(
                (dropout): Dropout(p=0.1, inplace=False)
                (lin1): Linear(in_features=768, out_features=3072, bias=True)
                (lin2): Linear(in_features=3072, out_features=768, bias=True)
                (activation): GELUActivation()
              )
              (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            )
          )
        )
      )
      (pre_classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=768, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=768, bias=True)
        )
      )
      (classifier): ModulesToSaveWrapper(
        (original_module): Linear(in_features=768, out_features=2, bias=True)
        (modules_to_save): ModuleDict(
          (default): Linear(in_features=768, out_features=2, bias=True)
        )
      )
      (dropout): Dropout(p=0.2, inplace=False)
    )
  )
)

See frozen base model

In [40]:
show_trainable_and_frozen(Grammatical_FT_LoRA_model)

Frozen: base_model.model.distilbert.embeddings.word_embeddings.weight
Frozen: base_model.model.distilbert.embeddings.position_embeddings.weight
Frozen: base_model.model.distilbert.embeddings.LayerNorm.weight
Frozen: base_model.model.distilbert.embeddings.LayerNorm.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: base_model.model.distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: base_model.model.distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.3.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.4.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.4.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.4.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.4.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.4.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.4.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.4.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.4.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.4.output_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.5.attention.q_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.q_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.q_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.q_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.k_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.k_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.k_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.k_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.v_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.v_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.v_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.v_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.out_lin.base_layer.weight
Frozen: base_model.model.distilbert.transformer.layer.5.attention.out_lin.base_layer.bias
Trainable: base_model.model.distilbert.transformer.layer.5.attention.out_lin.lora_A.default.weight
Trainable: base_model.model.distilbert.transformer.layer.5.attention.out_lin.lora_B.default.weight
Frozen: base_model.model.distilbert.transformer.layer.5.sa_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.5.sa_layer_norm.bias
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin1.weight
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin1.bias
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin2.weight
Frozen: base_model.model.distilbert.transformer.layer.5.ffn.lin2.bias
Frozen: base_model.model.distilbert.transformer.layer.5.output_layer_norm.weight
Frozen: base_model.model.distilbert.transformer.layer.5.output_layer_norm.bias
Frozen: base_model.model.pre_classifier.original_module.weight
Frozen: base_model.model.pre_classifier.original_module.bias
Trainable: base_model.model.pre_classifier.modules_to_save.default.weight
Trainable: base_model.model.pre_classifier.modules_to_save.default.bias
Frozen: base_model.model.classifier.original_module.weight
Frozen: base_model.model.classifier.original_module.bias
Trainable: base_model.model.classifier.modules_to_save.default.weight
Trainable: base_model.model.classifier.modules_to_save.default.bias

Train the model

In [41]:
training_args_Grammatical_FT_LoRA = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_FT_LoRA_model_3E_4_",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 3e-4,
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 6,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_FT_LoRA_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_FT_LoRA_model,
    args              = training_args_Grammatical_FT_LoRA,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Grammatical_FT_LoRA

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0003,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_FT_LoRA_model_3E_4_\runs\Feb09_20-44-09_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=6,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_FT_LoRA_model_3E_4_,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
import torch

# Force out-of-memory errors instead of spilling
#torch.cuda.set_per_process_memory_fraction(0.95, device=0)

# Disable memory growth that might cause spills
#os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:False'

# Check if you're spilling to CPU
#print(f"GPU Memory: {torch.cuda.memory_allocated(0)/1024**3:.2f} GB")


# If max_memory > 4GB, you're likely spilling or will crash

In [44]:
import torch

# Get device name
print(f"Device name: {torch.cuda.get_device_name(0)}")

# Current memory usage
allocated = torch.cuda.memory_allocated(0) / 1024**3
reserved = torch.cuda.memory_reserved(0) / 1024**3
total = torch.cuda.get_device_properties(0).total_memory / 1024**3

print(f"Allocated: {allocated:.2f} GB")
print(f"Reserved: {reserved:.2f} GB")
print(f"Total: {total:.2f} GB")
print(f"Free: {total - reserved:.2f} GB")
print(f"Max GPU Memory: {torch.cuda.max_memory_allocated(0)/1024**3:.2f} GB") # peak usage

Device name: NVIDIA GeForce GTX 1650
Allocated: 0.51 GB
Reserved: 0.54 GB
Total: 4.00 GB
Free: 3.46 GB
Max GPU Memory: 0.51 GB

In [45]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_FT_LoRA_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_FT_LoRA_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
2:03:49.999614
[7429.999613800028 Seconds]
________________________________________

# Feature Extraction 12 epochs

## Comprehensible

In [37]:
Comprehensible_DistilBertLast3LayerFusion_config = DistilBertConfig.from_pretrained(
                                                    "distilbert-base-multilingual-cased",
                                                    num_labels=2,
                                                    dropout=0.1,
                                                    attention_dropout=0.1,
                                                    seq_classif_dropout=0.1,
                                                )

Comprehensible_DistilBertLast3LayerFusion_model = DistilBertLast3LayerFusion.from_pretrained(
    "distilbert-base-multilingual-cased",
    config=Comprehensible_DistilBertLast3LayerFusion_config,
    ignore_mismatched_sizes=True  # important for custom head
)

Some weights of DistilBertLast3LayerFusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Comprehensible_DistilBertLast3LayerFusion_model) # See notes above on why ReLU activation does not show.

DistilBertLast3LayerFusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=4608, out_features=1024, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=1024, out_features=2, bias=True)
  )
)

Freeze all DestilBERT. We use only as Feature Extractor.

In [39]:
freeze_all_destilbert(Comprehensible_DistilBertLast3LayerFusion_model)

In [40]:
show_trainable_and_frozen(Comprehensible_DistilBertLast3LayerFusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Frozen: distilbert.transformer.layer.4.attention.q_lin.weight
Frozen: distilbert.transformer.layer.4.attention.q_lin.bias
Frozen: distilbert.transformer.layer.4.attention.k_lin.weight
Frozen: distilbert.transformer.layer.4.attention.k_lin.bias
Frozen: distilbert.transformer.layer.4.attention.v_lin.weight
Frozen: distilbert.transformer.layer.4.attention.v_lin.bias
Frozen: distilbert.transformer.layer.4.attention.out_lin.weight
Frozen: distilbert.transformer.layer.4.attention.out_lin.bias
Frozen: distilbert.transformer.layer.4.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.4.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.4.ffn.lin1.weight
Frozen: distilbert.transformer.layer.4.ffn.lin1.bias
Frozen: distilbert.transformer.layer.4.ffn.lin2.weight
Frozen: distilbert.transformer.layer.4.ffn.lin2.bias
Frozen: distilbert.transformer.layer.4.output_layer_norm.weight
Frozen: distilbert.transformer.layer.4.output_layer_norm.bias
Frozen: distilbert.transformer.layer.5.attention.q_lin.weight
Frozen: distilbert.transformer.layer.5.attention.q_lin.bias
Frozen: distilbert.transformer.layer.5.attention.k_lin.weight
Frozen: distilbert.transformer.layer.5.attention.k_lin.bias
Frozen: distilbert.transformer.layer.5.attention.v_lin.weight
Frozen: distilbert.transformer.layer.5.attention.v_lin.bias
Frozen: distilbert.transformer.layer.5.attention.out_lin.weight
Frozen: distilbert.transformer.layer.5.attention.out_lin.bias
Frozen: distilbert.transformer.layer.5.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.5.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.5.ffn.lin1.weight
Frozen: distilbert.transformer.layer.5.ffn.lin1.bias
Frozen: distilbert.transformer.layer.5.ffn.lin2.weight
Frozen: distilbert.transformer.layer.5.ffn.lin2.bias
Frozen: distilbert.transformer.layer.5.output_layer_norm.weight
Frozen: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [41]:
training_args_Comprehensible_DistilBertLast3LayerFusion_model = TrainingArguments(

    output_dir                 = "Saved_models/Comprehensible_FE_12_epochs",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 12,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBertLast3LayerFusion_model_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBertLast3LayerFusion_model,
    args              = training_args_Comprehensible_DistilBertLast3LayerFusion_model,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Comprehensible_DistilBertLast3LayerFusion_model

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Comprehensible_FE_12_epochs\runs\Feb06_06-24-50_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=12,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Comprehensible_FE_12_epochs,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBertLast3LayerFusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBertLast3LayerFusion_model_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
4:26:42.133486
[16002.133485800005 Seconds]
________________________________________

## Repetition

In [37]:
Repetition_free_DistilBertLast3LayerFusion_config = DistilBertConfig.from_pretrained(
                                                    "distilbert-base-multilingual-cased",
                                                    num_labels=2,
                                                    dropout=0.1,
                                                    attention_dropout=0.1,
                                                    seq_classif_dropout=0.1,
                                                )

Repetition_free_DistilBertLast3LayerFusion_model = DistilBertLast3LayerFusion.from_pretrained(
    "distilbert-base-multilingual-cased",
    config=Repetition_free_DistilBertLast3LayerFusion_config,
    ignore_mismatched_sizes=True  # important for custom head
)

Some weights of DistilBertLast3LayerFusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Repetition_free_DistilBertLast3LayerFusion_model) # See notes above on why ReLU activation does not show.

DistilBertLast3LayerFusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=4608, out_features=1024, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=1024, out_features=2, bias=True)
  )
)

Freeze all DestilBERT. We use only as Feature Extractor.

In [39]:
freeze_all_destilbert(Repetition_free_DistilBertLast3LayerFusion_model)

In [40]:
show_trainable_and_frozen(Repetition_free_DistilBertLast3LayerFusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Frozen: distilbert.transformer.layer.4.attention.q_lin.weight
Frozen: distilbert.transformer.layer.4.attention.q_lin.bias
Frozen: distilbert.transformer.layer.4.attention.k_lin.weight
Frozen: distilbert.transformer.layer.4.attention.k_lin.bias
Frozen: distilbert.transformer.layer.4.attention.v_lin.weight
Frozen: distilbert.transformer.layer.4.attention.v_lin.bias
Frozen: distilbert.transformer.layer.4.attention.out_lin.weight
Frozen: distilbert.transformer.layer.4.attention.out_lin.bias
Frozen: distilbert.transformer.layer.4.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.4.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.4.ffn.lin1.weight
Frozen: distilbert.transformer.layer.4.ffn.lin1.bias
Frozen: distilbert.transformer.layer.4.ffn.lin2.weight
Frozen: distilbert.transformer.layer.4.ffn.lin2.bias
Frozen: distilbert.transformer.layer.4.output_layer_norm.weight
Frozen: distilbert.transformer.layer.4.output_layer_norm.bias
Frozen: distilbert.transformer.layer.5.attention.q_lin.weight
Frozen: distilbert.transformer.layer.5.attention.q_lin.bias
Frozen: distilbert.transformer.layer.5.attention.k_lin.weight
Frozen: distilbert.transformer.layer.5.attention.k_lin.bias
Frozen: distilbert.transformer.layer.5.attention.v_lin.weight
Frozen: distilbert.transformer.layer.5.attention.v_lin.bias
Frozen: distilbert.transformer.layer.5.attention.out_lin.weight
Frozen: distilbert.transformer.layer.5.attention.out_lin.bias
Frozen: distilbert.transformer.layer.5.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.5.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.5.ffn.lin1.weight
Frozen: distilbert.transformer.layer.5.ffn.lin1.bias
Frozen: distilbert.transformer.layer.5.ffn.lin2.weight
Frozen: distilbert.transformer.layer.5.ffn.lin2.bias
Frozen: distilbert.transformer.layer.5.output_layer_norm.weight
Frozen: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [41]:
training_args_Repetition_free_DistilBertLast3LayerFusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_free_FE_12_epochs",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 12,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_free_DistilBertLast3LayerFusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_free_DistilBertLast3LayerFusion_model,
    args              = training_args_Repetition_free_DistilBertLast3LayerFusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Repetition_free_DistilBertLast3LayerFusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_free_FE_12_epochs\runs\Feb05_20-14-49_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=12,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_free_FE_12_epochs,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_free_DistilBertLast3LayerFusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_free_DistilBertLast3LayerFusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
3:06:56.551479
[11216.5514789 Seconds]
________________________________________

## Grammatical

In [37]:
Grammatical_DistilBertLast3LayerFusion_config = DistilBertConfig.from_pretrained(
                                                    "distilbert-base-multilingual-cased",
                                                    num_labels=2,
                                                    dropout=0.1,
                                                    attention_dropout=0.1,
                                                    seq_classif_dropout=0.1,
                                                )

Grammatical_DistilBertLast3LayerFusion_model = DistilBertLast3LayerFusion.from_pretrained(
    "distilbert-base-multilingual-cased",
    config=Grammatical_DistilBertLast3LayerFusion_config,
    ignore_mismatched_sizes=True  # important for custom head
)

Some weights of DistilBertLast3LayerFusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Grammatical_DistilBertLast3LayerFusion_model) # See notes above on why ReLU activation does not show.

DistilBertLast3LayerFusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=4608, out_features=1024, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=1024, out_features=2, bias=True)
  )
)

Freeze all DestilBERT. We use only as Feature Extractor.

In [39]:
freeze_all_destilbert(Grammatical_DistilBertLast3LayerFusion_model)

In [40]:
show_trainable_and_frozen(Grammatical_DistilBertLast3LayerFusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Frozen: distilbert.transformer.layer.4.attention.q_lin.weight
Frozen: distilbert.transformer.layer.4.attention.q_lin.bias
Frozen: distilbert.transformer.layer.4.attention.k_lin.weight
Frozen: distilbert.transformer.layer.4.attention.k_lin.bias
Frozen: distilbert.transformer.layer.4.attention.v_lin.weight
Frozen: distilbert.transformer.layer.4.attention.v_lin.bias
Frozen: distilbert.transformer.layer.4.attention.out_lin.weight
Frozen: distilbert.transformer.layer.4.attention.out_lin.bias
Frozen: distilbert.transformer.layer.4.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.4.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.4.ffn.lin1.weight
Frozen: distilbert.transformer.layer.4.ffn.lin1.bias
Frozen: distilbert.transformer.layer.4.ffn.lin2.weight
Frozen: distilbert.transformer.layer.4.ffn.lin2.bias
Frozen: distilbert.transformer.layer.4.output_layer_norm.weight
Frozen: distilbert.transformer.layer.4.output_layer_norm.bias
Frozen: distilbert.transformer.layer.5.attention.q_lin.weight
Frozen: distilbert.transformer.layer.5.attention.q_lin.bias
Frozen: distilbert.transformer.layer.5.attention.k_lin.weight
Frozen: distilbert.transformer.layer.5.attention.k_lin.bias
Frozen: distilbert.transformer.layer.5.attention.v_lin.weight
Frozen: distilbert.transformer.layer.5.attention.v_lin.bias
Frozen: distilbert.transformer.layer.5.attention.out_lin.weight
Frozen: distilbert.transformer.layer.5.attention.out_lin.bias
Frozen: distilbert.transformer.layer.5.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.5.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.5.ffn.lin1.weight
Frozen: distilbert.transformer.layer.5.ffn.lin1.bias
Frozen: distilbert.transformer.layer.5.ffn.lin2.weight
Frozen: distilbert.transformer.layer.5.ffn.lin2.bias
Frozen: distilbert.transformer.layer.5.output_layer_norm.weight
Frozen: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [42]:
training_args_Grammatical_DistilBertLast3LayerFusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_FE_12_epochs",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 12,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBertLast3LayerFusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBertLast3LayerFusion_model,
    args              = training_args_Grammatical_DistilBertLast3LayerFusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
training_args_Grammatical_DistilBertLast3LayerFusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_FE_12_epochs\runs\Feb06_00-11-51_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=12,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_FE_12_epochs,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [44]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBertLast3LayerFusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBertLast3LayerFusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
2:54:11.541531
[10451.541531099996 Seconds]
________________________________________

# Learning Rate (Comprehensible)

In [45]:
#5e-5 linear 0.3322

________________________________________
Training Time:
2:01:38.080620
[7298.080620199908 Seconds]
________________________________________

## 3e-5 cosine Loss 0.345000

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [41]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Comprehensible_Concat_LR_3E_5",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 3e-5, # LOWERED FROM 5e-5
    warmup_ratio  = 0.05, # LOWERED FROM 0.1
    lr_scheduler_type= "cosine", #changed from Linear

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=3e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Comprehensible_Concat_LR_3E_5\runs\Feb06_12-58-38_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.COSINE,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Comprehensible_Concat_LR_3E_5,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
2:23:02.708494
[8582.708494099992 Seconds]
________________________________________

## 1e-5 linear 0.399000

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [41]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Comprehensible_Concat_LR_1E_5",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-5, # LOWERED FROM 5e-5
    warmup_ratio  = 0.05, # LOWERED FROM 0.1
    lr_scheduler_type= "linear", #changed from Linear

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=1e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Comprehensible_Concat_LR_1E_5\runs\Feb06_15-39-20_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Comprehensible_Concat_LR_1E_5,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
2:22:10.731256
[8530.731256400002 Seconds]
________________________________________

## 1e-4 cosine 0.319100

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [44]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Comprehensible_Concat_LR_1E_4",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4, # LOWERED FROM 5e-5
    warmup_ratio  = 0.05, # LOWERED FROM 0.1
    lr_scheduler_type= "cosine", #changed from Linear

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [45]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Comprehensible_Concat_LR_1E_4\runs\Feb06_18-23-03_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.COSINE,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Comprehensible_Concat_LR_1E_4,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.01,
)

In [46]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
2:46:35.299739
[9995.299739300011 Seconds]
________________________________________

## 3e-4 cosine 0.373600

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [43]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Comprehensible_Concat_LR_3E_4",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 3e-4, # LOWERED FROM 5e-5
    warmup_ratio  = 0.05, # LOWERED FROM 0.1
    lr_scheduler_type= "cosine", #changed from Linear

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [44]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0003,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Comprehensible_Concat_LR_3E_4\runs\Feb06_21-49-18_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.COSINE,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Comprehensible_Concat_LR_3E_4,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.01,
)

In [45]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
2:14:56.577983
[8096.577983399999 Seconds]
________________________________________

## 1.5e-4 cosine 0.326900

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [41]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Comprehensible_Concat_LR_1_5E_4",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1.5e-4, # LOWERED FROM 5e-5
    warmup_ratio  = 0.1, # SAME FROM 0.1
    lr_scheduler_type= "cosine", #changed from Linear

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.00015,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Comprehensible_Concat_LR_1_5E_4\runs\Feb07_06-00-46_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.COSINE,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Comprehensible_Concat_LR_1_5E_4,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
2:15:10.546371
[8110.546371100005 Seconds]
________________________________________

# Learning Rate (Sum Fusion Repetition)

In [44]:
# 5 x 10^-5

________________________________________
Training Time:
1:21:23.758586
[4883.7585862998385 Seconds]
________________________________________

### 1e-4 linear 0.156500

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_LR_search_1",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_LR_search_1\runs\Feb10_01-19-50_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_LR_search_1,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:19:09.077687
[4749.077686700039 Seconds]
________________________________________

### 1e-5 linear 0.253500

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [43]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_LR_search_1_e_5_linear",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-5,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [44]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=1e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_LR_search_1_e_5_linear\runs\Feb10_03-08-51_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_LR_search_1_e_5_linear,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.01,
)

In [45]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:21:53.362773
[4913.36277300003 Seconds]
________________________________________

### 3e-4 linear 0.196000

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_LR_search_Sum_3e_4_linear",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 3e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0003,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_LR_search_Sum_3e_4_linear\runs\Feb10_09-54-35_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_LR_search_Sum_3e_4_linear,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:32:22.743587
[5542.743587199948 Seconds]
________________________________________

### 7.5e-5 cosine 	0.164200

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_LR_search_7_5_e_5",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 7.5e-5,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "cosine",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=7.5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_LR_search_7_5_e_5\runs\Feb10_12-22-25_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.COSINE,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_LR_search_7_5_e_5,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:20:01.920017
[4801.920017099939 Seconds]
________________________________________

# Learning Rate (Grammatical)

In [44]:
# 1e-5 linear

________________________________________
Training Time:
1:21:42.271721
[4902.271721499972 Seconds]
________________________________________

## 1e-4 linear 0.439800

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_Sum_LR_1E_4",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_Sum_LR_1E_4\runs\Feb10_14-17-43_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_Sum_LR_1E_4,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:24:31.149883
[5071.149882599944 Seconds]
________________________________________

## 7.5E-5 0.472900

In [38]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [40]:
freeze_first_n_layers(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [41]:
show_trainable_and_frozen(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [44]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_Sum_LR_7_5_e_5",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 7.5e-5,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [45]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=7.5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_Sum_LR_7_5_e_5\runs\Feb10_19-53-12_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_Sum_LR_7_5_e_5,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.01,
)

In [46]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:32:58.231635
[5578.231634699972 Seconds]
________________________________________

## 1.5E-4 cosine 0.448200

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_Sum_LR_1_5_E_4",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1.5e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "cosine",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.00015,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_Sum_LR_1_5_E_4\runs\Feb10_21-55-13_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.COSINE,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_Sum_LR_1_5_E_4,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:40:36.363063
[6036.363062900025 Seconds]
________________________________________

## 3E-4 cosine 0.554700

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_Sum_LR_3_E_4",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 3e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "cosine",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0003,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_Sum_LR_3_E_4\runs\Feb11_02-05-51_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.COSINE,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_Sum_LR_3_E_4,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
2:12:05.563150
[7925.563149700058 Seconds]
________________________________________

# Regularization

## Comprehensible Concat 2 Layers

0.892478

In [46]:
# 1e-4

________________________________________
Training Time:
2:46:35.299739
[9995.299739300011 Seconds]
________________________________________

## 0.892266

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.1,  # Embeddings
    attention_dropout   = 0.2,  # Transformer
    seq_classif_dropout = 0.4,  # Classification head
)

# Load model with custom config
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.2, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.4, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [41]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Reg_search_comprehensible_1",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4, # LOWERED FROM 5e-5
    warmup_ratio  = 0.05, # LOWERED FROM 0.1
    lr_scheduler_type= "cosine", #changed from Linear

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.05  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Reg_search_comprehensible_1\runs\Feb11_11-33-32_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.COSINE,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Reg_search_comprehensible_1,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.05,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
2:09:34.098082
[7774.0980824 Seconds]
________________________________________

## 0.890647

In [42]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.2,  # Embeddings
    attention_dropout   = 0.25,  # Transformer
    seq_classif_dropout = 0.4,  # Classification head
)

# Load model with custom config
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [43]:
print(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.2, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.25, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.2, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.4, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 4 layers

In [44]:
freeze_first_n_layers(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 4)

In [45]:
show_trainable_and_frozen(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [46]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Reg_search_comprehensible_2",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4, # LOWERED FROM 5e-5
    warmup_ratio  = 0.05, # LOWERED FROM 0.1
    lr_scheduler_type= "cosine", #changed from Linear

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.1  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [47]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Reg_search_comprehensible_2\runs\Feb11_13-48-27_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.COSINE,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Reg_search_comprehensible_2,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.1,
)

In [48]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:57:49.673946
[7069.6739462000005 Seconds]
________________________________________

## 0.890974

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.15,  # Embeddings
    attention_dropout   = 0.1,  # Transformer
    seq_classif_dropout = 0.3,  # Classification head
)

# Load model with custom config
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.15, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.15, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.3, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [41]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Reg_search_comprehensible_3",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4, # LOWERED FROM 5e-5
    warmup_ratio  = 0.05, # LOWERED FROM 0.1
    lr_scheduler_type= "cosine", #changed from Linear

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.005  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Reg_search_comprehensible_3\runs\Feb11_15-57-05_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.COSINE,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Reg_search_comprehensible_3,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.005,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
2:06:08.237271
[7568.237270900001 Seconds]
________________________________________

## 0.891234

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.05,  # Embeddings
    attention_dropout   = 0.05,  # Transformer
    seq_classif_dropout = 0.1,  # Classification head
)

# Load model with custom config
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.05, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.05, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.05, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [43]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Reg_search_comprehensible_low_reg",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4, # LOWERED FROM 5e-5
    warmup_ratio  = 0.05, # LOWERED FROM 0.1
    lr_scheduler_type= "cosine", #changed from Linear

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.005  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [44]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Reg_search_comprehensible_low_reg\runs\Feb11_18-15-36_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.COSINE,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Reg_search_comprehensible_low_reg,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.005,
)

In [45]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
2:26:40.523147
[8800.523146900003 Seconds]
________________________________________

## 0.893530

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.075,  # Embeddings
    attention_dropout   = 0.075,  # Transformer
    seq_classif_dropout = 0.25,  # Classification head
)

# Load model with custom config
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Concat_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Concat_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Concat_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.075, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.075, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.075, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=1536, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.25, inplace=False)
    (3): Linear(in_features=768, out_features=2, bias=True)
  )
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [43]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Reg_search_comprehensible_0025_wd_01",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4, # LOWERED FROM 5e-5
    warmup_ratio  = 0.05, # LOWERED FROM 0.1
    lr_scheduler_type= "cosine", #changed from Linear

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.05  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model,
    args              = training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion,
    train_dataset     = tokenized_comprehensible_train,
    eval_dataset      = tokenized_comprehensible_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_comprehensible,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [44]:
training_args_Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Reg_search_comprehensible_0025_wd_01\runs\Feb13_14-30-06_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.COSINE,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Reg_search_comprehensible_0025_wd_01,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.05,
)

In [45]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Comprehensible_DistilBert_CLS_and_AVG_Pooling_Concat_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
2:07:31.384415
[7651.384415200009 Seconds]
________________________________________

# Repetition

In [43]:
# previous

________________________________________
Training Time:
1:19:09.077687
[4749.077686700039 Seconds]
________________________________________

### 0.965335

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.2,  # Embeddings
    attention_dropout   = 0.2,  # Transformer
    seq_classif_dropout = 0.4,  # Classification head
)

# Load model with custom config
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.2, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.2, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.2, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.4, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.4, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_REG_search_1_02",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.005  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_REG_search_1_02\runs\Feb11_22-58-50_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_REG_search_1_02,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.005,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:53:05.480614
[6785.480614300002 Seconds]
________________________________________

### 0.964389

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.15,  # Embeddings
    attention_dropout   = 0.15,  # Transformer
    seq_classif_dropout = 0.4,  # Classification head
)

# Load model with custom config
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [43]:
print(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.15, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.15, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.15, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.4, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.4, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [44]:
freeze_first_n_layers(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [45]:
show_trainable_and_frozen(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [46]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_REG_search_2",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [47]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_REG_search_2\runs\Feb12_01-32-19_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_REG_search_2,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.01,
)

In [48]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:49:37.667251
[6577.667250899998 Seconds]
________________________________________

### 0.965403

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.05,  # Embeddings
    attention_dropout   = 0.05,  # Transformer
    seq_classif_dropout = 0.2,  # Classification head
)

# Load model with custom config
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.05, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.05, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.05, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.2, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.2, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_REG_search_4",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.05  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_REG_search_4\runs\Feb12_09-41-03_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_REG_search_4,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.05,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:40:31.894969
[6031.894969300003 Seconds]
________________________________________

### 0.962755

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.25,  # Embeddings
    attention_dropout   = 0.25,  # Transformer
    seq_classif_dropout = 0.25,  # Classification head
)

# Load model with custom config
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.25, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.25, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.25, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.25, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.25, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_REG_search_5",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.1  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_REG_search_5\runs\Feb12_11-26-34_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_REG_search_5,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.1,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:37:20.720505
[5840.720504500001 Seconds]
________________________________________

### 0.962755

In [43]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.3,  # Embeddings
    attention_dropout   = 0.3,  # Transformer
    seq_classif_dropout = 0.3,  # Classification head
)

# Load model with custom config
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [44]:
print(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.3, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.3, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.3, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.3, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.3, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [45]:
freeze_first_n_layers(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [46]:
show_trainable_and_frozen(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [47]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_REG_search_6",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.05  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [48]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_REG_search_6\runs\Feb12_14-21-57_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_REG_search_6,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.05,
)

In [49]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:32:51.826208
[5571.826208099999 Seconds]
________________________________________

### 0.966313

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.075,  # Embeddings
    attention_dropout   = 0.075,  # Transformer
    seq_classif_dropout = 0.25,  # Classification head
)

# Load model with custom config
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.075, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.075, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.075, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.25, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.25, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Repetition_REG_search_wd_01_d_0025",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.1  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_repetition_train,
    eval_dataset      = tokenized_repetition_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_repetition,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Repetition_REG_search_wd_01_d_0025\runs\Feb13_13-03-40_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Repetition_REG_search_wd_01_d_0025,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.1,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Repetition_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:21:15.606358
[4875.606358299992 Seconds]
________________________________________

# Grammatical

In [43]:
#previous

________________________________________
Training Time:
1:24:31.149883
[5071.149882599944 Seconds]
________________________________________

## 0.781895

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.2,  # Embeddings
    attention_dropout   = 0.2,  # Transformer
    seq_classif_dropout = 0.3,  # Classification head
)

# Load model with custom config
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.2, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.2, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.2, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.3, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.3, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_Sum_LR_1E_4_REG_1",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.05  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_Sum_LR_1E_4_REG_1\runs\Feb12_19-18-13_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_Sum_LR_1E_4_REG_1,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.05,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:35:19.161821
[5719.161820699999 Seconds]
________________________________________

## 0.786065

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.05,  # Embeddings
    attention_dropout   = 0.05,  # Transformer
    seq_classif_dropout = 0.05,  # Classification head
)

# Load model with custom config
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.05, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.05, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.05, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.05, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.05, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_Sum_LR_1E_4_REG_2",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_Sum_LR_1E_4_REG_2\runs\Feb12_21-54-12_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_Sum_LR_1E_4_REG_2,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.01,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:45:36.339059
[6336.339058500002 Seconds]
________________________________________

## 1e-4 linear 0.786600

In [38]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.15,  # Embeddings
    attention_dropout   = 0.15,  # Transformer
    seq_classif_dropout = 0.15,  # Classification head
)

# Load model with custom config
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [39]:
print(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.15, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.15, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.15, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.15, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.15, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [40]:
freeze_first_n_layers(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [41]:
show_trainable_and_frozen(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [42]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_Sum_LR_1E_4_REG_3",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.03  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [43]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_Sum_LR_1E_4_REG_3\runs\Feb13_04-33-54_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_Sum_LR_1E_4_REG_3,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.03,
)

In [44]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:31:05.777285
[5465.777284699987 Seconds]
________________________________________

## 1e-4 linear 0.787007

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.075,  # Embeddings
    attention_dropout   = 0.075,  # Transformer
    seq_classif_dropout = 0.25,  # Classification head
)

# Load model with custom config
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.075, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.075, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.075, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.25, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.25, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_Sum_LR_1E_4_REG_4",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.1  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_Sum_LR_1E_4_REG_4\runs\Feb13_06-10-35_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_Sum_LR_1E_4_REG_4,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.1,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:22:40.618588
[4960.618587600009 Seconds]
________________________________________

## 0.785506

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.015,  # Embeddings
    attention_dropout   = 0.015,  # Transformer
    seq_classif_dropout = 0.25,  # Classification head
)

# Load model with custom config
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.015, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.015, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.015, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.25, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.25, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_Sum_LR_1E_4_REG_5",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.15  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_Sum_LR_1E_4_REG_5\runs\Feb13_10-02-12_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_Sum_LR_1E_4_REG_5,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.15,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:26:09.429851
[5169.429850799992 Seconds]
________________________________________

## 0.786270

In [37]:
from transformers import DistilBertForSequenceClassification, DistilBertConfig

# Create custom config with dropout values
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config = DistilBertConfig.from_pretrained(
    'distilbert-base-multilingual-cased',
    num_labels          = 2,    # Binary classification
    dropout             = 0.025,  # Embeddings
    attention_dropout   = 0.025,  # Transformer
    seq_classif_dropout = 0.025,  # Classification head
)

# Load model with custom config
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model = DistilBert_CLS_and_AVG_Pooling_Sum_Fusion.from_pretrained(
                                                   'distilbert-base-multilingual-cased',
                                                    config=Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_config,
                                                    ignore_mismatched_sizes=True  # Important! Since we have custom layers
)

Some weights of DistilBert_CLS_and_AVG_Pooling_Sum_Fusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['avg_head.0.bias', 'avg_head.0.weight', 'cls_head.0.bias', 'cls_head.0.weight', 'merge_classifier.bias', 'merge_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [38]:
print(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model) # See notes above on why ReLU activation does not show.

DistilBert_CLS_and_AVG_Pooling_Sum_Fusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.025, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.025, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.025, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (cls_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.025, inplace=False)
  )
  (avg_head): Sequential(
    (0): Linear(in_features=768, out_features=768, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.025, inplace=False)
  )
  (merge_classifier): Linear(in_features=768, out_features=2, bias=True)
)

Freeze 4 layers

In [39]:
freeze_first_n_layers(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model, 4)

In [40]:
show_trainable_and_frozen(Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Trainable: distilbert.transformer.layer.4.attention.q_lin.weight
Trainable: distilbert.transformer.layer.4.attention.q_lin.bias
Trainable: distilbert.transformer.layer.4.attention.k_lin.weight
Trainable: distilbert.transformer.layer.4.attention.k_lin.bias
Trainable: distilbert.transformer.layer.4.attention.v_lin.weight
Trainable: distilbert.transformer.layer.4.attention.v_lin.bias
Trainable: distilbert.transformer.layer.4.attention.out_lin.weight
Trainable: distilbert.transformer.layer.4.attention.out_lin.bias
Trainable: distilbert.transformer.layer.4.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.4.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.4.ffn.lin1.weight
Trainable: distilbert.transformer.layer.4.ffn.lin1.bias
Trainable: distilbert.transformer.layer.4.ffn.lin2.weight
Trainable: distilbert.transformer.layer.4.ffn.lin2.bias
Trainable: distilbert.transformer.layer.4.output_layer_norm.weight
Trainable: distilbert.transformer.layer.4.output_layer_norm.bias
Trainable: distilbert.transformer.layer.5.attention.q_lin.weight
Trainable: distilbert.transformer.layer.5.attention.q_lin.bias
Trainable: distilbert.transformer.layer.5.attention.k_lin.weight
Trainable: distilbert.transformer.layer.5.attention.k_lin.bias
Trainable: distilbert.transformer.layer.5.attention.v_lin.weight
Trainable: distilbert.transformer.layer.5.attention.v_lin.bias
Trainable: distilbert.transformer.layer.5.attention.out_lin.weight
Trainable: distilbert.transformer.layer.5.attention.out_lin.bias
Trainable: distilbert.transformer.layer.5.sa_layer_norm.weight
Trainable: distilbert.transformer.layer.5.sa_layer_norm.bias
Trainable: distilbert.transformer.layer.5.ffn.lin1.weight
Trainable: distilbert.transformer.layer.5.ffn.lin1.bias
Trainable: distilbert.transformer.layer.5.ffn.lin2.weight
Trainable: distilbert.transformer.layer.5.ffn.lin2.bias
Trainable: distilbert.transformer.layer.5.output_layer_norm.weight
Trainable: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: cls_head.0.weight
Trainable: cls_head.0.bias
Trainable: avg_head.0.weight
Trainable: avg_head.0.bias
Trainable: merge_classifier.weight
Trainable: merge_classifier.bias

Train the model

In [41]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion = TrainingArguments(

    output_dir                 = "Saved_models/Grammatical_Sum_LR_1E_4_REG_6",
    eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    learning_rate = 1e-4,
    warmup_ratio  = 0.05,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.15  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model,
    args              = training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion,
    train_dataset     = tokenized_grammar_train,
    eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = inverse_frequency_class_weights_grammar,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [42]:
training_args_Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=True,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.EPOCH,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=False,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=0.0001,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=True,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/Grammatical_Sum_LR_1E_4_REG_6\runs\Feb13_11-33-58_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=loss,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/Grammatical_Sum_LR_1E_4_REG_6,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.05,
warmup_steps=0,
weight_decay=0.15,
)

In [43]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBert_CLS_and_AVG_Pooling_Sum_Fusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
1:22:50.792892
[4970.792891999998 Seconds]
________________________________________

# MELA

# MELA

In [1]:

import zipfile
import os
import wget
from datasets import load_dataset,Dataset
import os
from pathlib import Path
import pandas as pd

url =  "https://github.com/sjtu-compling/MELA/raw/refs/heads/main/data.zip"
filename = wget.download(url)

os.makedirs("MELA", exist_ok=True)
password = "200240"
with zipfile.ZipFile("data.zip", 'r') as zip_ref:
      zip_ref.extractall("MELA/",pwd=password.encode('utf-8'))

In [2]:
from datasets import concatenate_datasets

MELA_all_languages = ['en', 'zh', 'it', 'ru', 'de', 'fr', 'es', 'ja', 'ar', 'is']
MELA_languages_intersection = ['en', 'ru', 'de', 'es']
datasets_mela_intersection = []
datasets_mela_all_languages = []
mela_train_all =[]
mela_dev_all =[]
mela_test_all =[]


for language_i in MELA_languages_intersection:
    MELA_dataset_i = load_dataset(
        "csv",
        data_files = {
            "train": "MELA/data/v1.0/" + language_i + "/train.csv",
            "validation": "MELA/data/v1.0/" + language_i + "/dev.csv",
            "test": "MELA/data/v1.0/" + language_i + "/test.csv"
        }
    )

    MELA_dataset_i = MELA_dataset_i.select_columns(["sentence","label"])
    MELA_joint = concatenate_datasets([
        MELA_dataset_i["train"],
        MELA_dataset_i["validation"],
        MELA_dataset_i["test"]
    ]).to_pandas()

    datasets_mela_intersection.append(MELA_joint)


for language_i in MELA_all_languages:
    MELA_dataset_i = load_dataset(
        "csv",
        data_files = {
            "train": "MELA/data/v1.0/" + language_i + "/train.csv",
            "validation": "MELA/data/v1.0/" + language_i + "/dev.csv",
            "test": "MELA/data/v1.0/" + language_i + "/test.csv"
        }
    )

    MELA_dataset_i = MELA_dataset_i.select_columns(["sentence","label"])
    MELA_joint = concatenate_datasets([
        MELA_dataset_i["train"],
        MELA_dataset_i["validation"],
        MELA_dataset_i["test"]
    ]).to_pandas()

    mela_train_all.append(MELA_dataset_i["train"].to_pandas())
    mela_dev_all.append(MELA_dataset_i["validation"].to_pandas())
    mela_test_all.append(MELA_dataset_i["test"].to_pandas())

    print(language_i, len(MELA_joint))

    datasets_mela_all_languages.append(MELA_joint)

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

en 9594

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

zh 7495

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

it 9722
ru 11501
de 1045

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

fr 1433
es 1088

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

ja 1661

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

ar 1017

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

Generating test split: 0 examples [00:00, ? examples/s]

is 2298

In [3]:
mela_train_all = pd.concat(mela_train_all, ignore_index=True)
mela_dev_all = pd.concat(mela_dev_all, ignore_index=True)
mela_test_all = pd.concat(mela_test_all, ignore_index=True)

len(mela_train_all), len(mela_dev_all), len(mela_test_all)

(33293, 6140, 7421)

In [4]:
mela_dev_all["label"].value_counts()

label
1    4741
0    1399
Name: count, dtype: int64

In [5]:
(1.2950854250158195 + 4.388849177984274)

5.683934603000093

In [6]:
(1/(4741/6140))/5.68,  (1/(1399/6140))/5.68

(0.22800799736194005, 0.7726847144338511)

In [7]:
mela_weighs = torch.tensor([0.7726847144338511, 0.22800799736194005])

NameError: name 'torch' is not defined

In [40]:
mela_train_all_X = mela_train_all["sentence"]
mela_train_all_y = mela_train_all["label"]

In [41]:
MELA_intersection = pd.concat(datasets_mela_intersection, ignore_index=True)
MELA_all_languages = pd.concat(datasets_mela_all_languages, ignore_index=True)

In [42]:
len(MELA_intersection), len(MELA_all_languages)

(23228, 46854)

In [43]:
MELA_all_languages["label"].value_counts()

label
1    34977
0    11877
Name: count, dtype: int64

In [44]:
MELA_intersection["label"].value_counts()

label
1    16734
0     6494
Name: count, dtype: int64

In [45]:
MELA_intersection_X = MELA_intersection["sentence"]
MELA_intersection_y = MELA_intersection["label"]

MELA_all_languages_X = MELA_all_languages["sentence"]
MELA_all_languages_y = MELA_all_languages["label"]

## Grammatical

In [46]:
Grammatical_DistilBertLast3LayerFusion_config = DistilBertConfig.from_pretrained(
                                                    "distilbert-base-multilingual-cased",
                                                    num_labels=2,
                                                    dropout=0.1,
                                                    attention_dropout=0.1,
                                                    seq_classif_dropout=0.1,
                                                )

Grammatical_DistilBertLast3LayerFusion_model = DistilBertLast3LayerFusion.from_pretrained(
    "distilbert-base-multilingual-cased",
    config=Grammatical_DistilBertLast3LayerFusion_config,
    ignore_mismatched_sizes=True  # important for custom head
)

Some weights of DistilBertLast3LayerFusion were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['merge_classifier.0.bias', 'merge_classifier.0.weight', 'merge_classifier.3.bias', 'merge_classifier.3.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Inspect architecture

In [47]:
print(Grammatical_DistilBertLast3LayerFusion_model) # See notes above on why ReLU activation does not show.

DistilBertLast3LayerFusion(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSdpaAttention(
            (dropout): Dropout(p=0.1, inplace=False)
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (merge_classifier): Sequential(
    (0): Linear(in_features=4608, out_features=1024, bias=True)
    (1): GELU(approximate='none')
    (2): Dropout(p=0.1, inplace=False)
    (3): Linear(in_features=1024, out_features=2, bias=True)
  )
)

Freeze all DestilBERT. We use only as Feature Extractor.

In [48]:
freeze_all_destilbert(Grammatical_DistilBertLast3LayerFusion_model)

In [49]:
show_trainable_and_frozen(Grammatical_DistilBertLast3LayerFusion_model)

Frozen: distilbert.embeddings.word_embeddings.weight
Frozen: distilbert.embeddings.position_embeddings.weight
Frozen: distilbert.embeddings.LayerNorm.weight
Frozen: distilbert.embeddings.LayerNorm.bias
Frozen: distilbert.transformer.layer.0.attention.q_lin.weight
Frozen: distilbert.transformer.layer.0.attention.q_lin.bias
Frozen: distilbert.transformer.layer.0.attention.k_lin.weight
Frozen: distilbert.transformer.layer.0.attention.k_lin.bias
Frozen: distilbert.transformer.layer.0.attention.v_lin.weight
Frozen: distilbert.transformer.layer.0.attention.v_lin.bias
Frozen: distilbert.transformer.layer.0.attention.out_lin.weight
Frozen: distilbert.transformer.layer.0.attention.out_lin.bias
Frozen: distilbert.transformer.layer.0.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.0.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.0.ffn.lin1.weight
Frozen: distilbert.transformer.layer.0.ffn.lin1.bias
Frozen: distilbert.transformer.layer.0.ffn.lin2.weight
Frozen: distilbert.transformer.layer.0.ffn.lin2.bias
Frozen: distilbert.transformer.layer.0.output_layer_norm.weight
Frozen: distilbert.transformer.layer.0.output_layer_norm.bias
Frozen: distilbert.transformer.layer.1.attention.q_lin.weight
Frozen: distilbert.transformer.layer.1.attention.q_lin.bias
Frozen: distilbert.transformer.layer.1.attention.k_lin.weight
Frozen: distilbert.transformer.layer.1.attention.k_lin.bias
Frozen: distilbert.transformer.layer.1.attention.v_lin.weight
Frozen: distilbert.transformer.layer.1.attention.v_lin.bias
Frozen: distilbert.transformer.layer.1.attention.out_lin.weight
Frozen: distilbert.transformer.layer.1.attention.out_lin.bias
Frozen: distilbert.transformer.layer.1.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.1.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.1.ffn.lin1.weight
Frozen: distilbert.transformer.layer.1.ffn.lin1.bias
Frozen: distilbert.transformer.layer.1.ffn.lin2.weight
Frozen: distilbert.transformer.layer.1.ffn.lin2.bias
Frozen: distilbert.transformer.layer.1.output_layer_norm.weight
Frozen: distilbert.transformer.layer.1.output_layer_norm.bias
Frozen: distilbert.transformer.layer.2.attention.q_lin.weight
Frozen: distilbert.transformer.layer.2.attention.q_lin.bias
Frozen: distilbert.transformer.layer.2.attention.k_lin.weight
Frozen: distilbert.transformer.layer.2.attention.k_lin.bias
Frozen: distilbert.transformer.layer.2.attention.v_lin.weight
Frozen: distilbert.transformer.layer.2.attention.v_lin.bias
Frozen: distilbert.transformer.layer.2.attention.out_lin.weight
Frozen: distilbert.transformer.layer.2.attention.out_lin.bias
Frozen: distilbert.transformer.layer.2.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.2.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.2.ffn.lin1.weight
Frozen: distilbert.transformer.layer.2.ffn.lin1.bias
Frozen: distilbert.transformer.layer.2.ffn.lin2.weight
Frozen: distilbert.transformer.layer.2.ffn.lin2.bias
Frozen: distilbert.transformer.layer.2.output_layer_norm.weight
Frozen: distilbert.transformer.layer.2.output_layer_norm.bias
Frozen: distilbert.transformer.layer.3.attention.q_lin.weight
Frozen: distilbert.transformer.layer.3.attention.q_lin.bias
Frozen: distilbert.transformer.layer.3.attention.k_lin.weight
Frozen: distilbert.transformer.layer.3.attention.k_lin.bias
Frozen: distilbert.transformer.layer.3.attention.v_lin.weight
Frozen: distilbert.transformer.layer.3.attention.v_lin.bias
Frozen: distilbert.transformer.layer.3.attention.out_lin.weight
Frozen: distilbert.transformer.layer.3.attention.out_lin.bias
Frozen: distilbert.transformer.layer.3.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.3.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.3.ffn.lin1.weight
Frozen: distilbert.transformer.layer.3.ffn.lin1.bias
Frozen: distilbert.transformer.layer.3.ffn.lin2.weight
Frozen: distilbert.transformer.layer.3.ffn.lin2.bias
Frozen: distilbert.transformer.layer.3.output_layer_norm.weight
Frozen: distilbert.transformer.layer.3.output_layer_norm.bias
Frozen: distilbert.transformer.layer.4.attention.q_lin.weight
Frozen: distilbert.transformer.layer.4.attention.q_lin.bias
Frozen: distilbert.transformer.layer.4.attention.k_lin.weight
Frozen: distilbert.transformer.layer.4.attention.k_lin.bias
Frozen: distilbert.transformer.layer.4.attention.v_lin.weight
Frozen: distilbert.transformer.layer.4.attention.v_lin.bias
Frozen: distilbert.transformer.layer.4.attention.out_lin.weight
Frozen: distilbert.transformer.layer.4.attention.out_lin.bias
Frozen: distilbert.transformer.layer.4.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.4.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.4.ffn.lin1.weight
Frozen: distilbert.transformer.layer.4.ffn.lin1.bias
Frozen: distilbert.transformer.layer.4.ffn.lin2.weight
Frozen: distilbert.transformer.layer.4.ffn.lin2.bias
Frozen: distilbert.transformer.layer.4.output_layer_norm.weight
Frozen: distilbert.transformer.layer.4.output_layer_norm.bias
Frozen: distilbert.transformer.layer.5.attention.q_lin.weight
Frozen: distilbert.transformer.layer.5.attention.q_lin.bias
Frozen: distilbert.transformer.layer.5.attention.k_lin.weight
Frozen: distilbert.transformer.layer.5.attention.k_lin.bias
Frozen: distilbert.transformer.layer.5.attention.v_lin.weight
Frozen: distilbert.transformer.layer.5.attention.v_lin.bias
Frozen: distilbert.transformer.layer.5.attention.out_lin.weight
Frozen: distilbert.transformer.layer.5.attention.out_lin.bias
Frozen: distilbert.transformer.layer.5.sa_layer_norm.weight
Frozen: distilbert.transformer.layer.5.sa_layer_norm.bias
Frozen: distilbert.transformer.layer.5.ffn.lin1.weight
Frozen: distilbert.transformer.layer.5.ffn.lin1.bias
Frozen: distilbert.transformer.layer.5.ffn.lin2.weight
Frozen: distilbert.transformer.layer.5.ffn.lin2.bias
Frozen: distilbert.transformer.layer.5.output_layer_norm.weight
Frozen: distilbert.transformer.layer.5.output_layer_norm.bias
Trainable: merge_classifier.0.weight
Trainable: merge_classifier.0.bias
Trainable: merge_classifier.3.weight
Trainable: merge_classifier.3.bias

Train the model

In [83]:
training_args_Grammatical_DistilBertLast3LayerFusion = TrainingArguments(

    output_dir                 = "Saved_models/MELA_FE",
    #eval_strategy              = "epoch",
    save_strategy              = "epoch",
    per_device_eval_batch_size = 32,
    #load_best_model_at_end     = True,

    # Reproducibility
    seed=42,       # Training randomness for weights and dropout.
    data_seed=42,  # Randomness for sampling-shuffling data.

    #Learning rate behaviour
    #learning_rate = default
    warmup_ratio  = 0.1,
    lr_scheduler_type= "linear",

    num_train_epochs            = 4,
    per_device_train_batch_size = 32,

    weight_decay=0.01  # Regularization

    #Other params that we do not use
    #push_to_hub --> upload to HuggingFace
    #gradient_accumulation_steps--> Effective batch size = batch * accumulation_steps

)

Grammatical_DistilBertLast3LayerFusion_trainer = WeightedCrossEntropyTrainer(
    model             = Grammatical_DistilBertLast3LayerFusion_model,
    args              = training_args_Grammatical_DistilBertLast3LayerFusion,
    train_dataset     = dataset_mela_tokenized,
    #eval_dataset      = tokenized_grammar_validation,
    processing_class  = tokenizer,
    data_collator     = data_collator,
    compute_metrics   = compute_metrics,

    class_weights     = mela_weighs,

)

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

In [75]:
def tokenize_function_mela(examples):
    return tokenizer(examples["sentence"], truncation=True, max_length=512)

dataset_mela = Dataset.from_pandas(mela_train_all.rename(columns={"label": "labels"}))
dataset_mela_tokenized = dataset_mela.map(tokenize_function_mela, batched=True)

Map:   0%|          | 0/33293 [00:00<?, ? examples/s]

In [77]:
mela_train_all.rename(columns={"label": "labels"})

                                                sentence  labels
0      Our friends won't buy this analysis, let alone...       1
1      One more pseudo generalization and I'm giving up.       1
2       One more pseudo generalization or I'm giving up.       1
3         The more we study verbs, the crazier they get.       1
4              Day by day the facts are getting murkier.       1
...                                                  ...     ...
33288      Það var haldið sig innan dyra út af óveðrinu.       1
33289   Þetta eru allar hinar þínar þrjár nýju kenningar       0
33290                 Ég tel hafa verið mýs í baðkerinu.       1
33291         Í þessari ritgerð ætla ég að kynna bókina.       1
33292                               Það var barið strák.       1

[33293 rows x 2 columns]

In [78]:
training_args_Grammatical_DistilBertLast3LayerFusion

TrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=True,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=42,
dataloader_drop_last=False,
dataloader_num_workers=0,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
do_eval=False,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.NO,
eval_use_gather_object=False,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=None,
hub_revision=None,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=no,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
liger_kernel_config=None,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=Saved_models/MELA_FE\runs\Feb22_17-46-33_LAPTOP-RP8A2UEC,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=4,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=Saved_models/MELA_FE,
overwrite_output_dir=False,
parallelism_config=None,
past_index=-1,
per_device_eval_batch_size=32,
per_device_train_batch_size=32,
prediction_loss_only=False,
project=huggingface,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=[],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=None,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=SaveStrategy.EPOCH,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
trackio_space_id=trackio,
use_cpu=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.1,
warmup_steps=0,
weight_decay=0.01,
)

In [84]:
os.makedirs("Saved_models", exist_ok=True)  # create folder if not existing yet.
Grammatical_DistilBertLast3LayerFusion_model.train()     # Set train mode On

start = time.perf_counter()  # Start point for time Track
Grammatical_DistilBertLast3LayerFusion_trainer.train()              # Train the model
torch.cuda.synchronize()     # Compute and print time spent training
end = time.perf_counter()
elapsed = end - start
print_training_time(elapsed)

________________________________________
Training Time:
0:06:50.511579
[410.51157859998057 Seconds]
________________________________________

In [45]:


#Feature Extraction using frozen base model taking representative vector from 3 last layers.
Grammatical_DistilBertLast3LayerFusion_reload = DistilBertLast3LayerFusion.from_pretrained(
    "Saved_models/MELA_FE/checkpoint-4164"
)

In [46]:
input_text_tokenizer_reloaded = AutoTokenizer.from_pretrained("Saved_models_FT_and_FE/Comprehensible_DBSC_FT_3_layers/checkpoint-3780")
#Any checkpoint ok as all are default DistilBERT Multilingual cased Tokenizer.

The tokenizer you are loading from 'Saved_models_FT_and_FE/Comprehensible_DBSC_FT_3_layers/checkpoint-3780' with an incorrect regex pattern: https://huggingface.co/mistralai/Mistral-Small-3.1-24B-Instruct-2503/discussions/84#69121093e8b480e709447d5e. This will lead to incorrect tokenization. You should set the `fix_mistral_regex=True` flag when loading this tokenizer to fix this issue.

#  .

In [47]:
grammatical_model_for_inference_list = \
    [
     Grammatical_DistilBertLast3LayerFusion_reload,

     ]

grammatical_model_names = \
    [
     "Grammatical_DistilBertLast3LayerFusion_reload"

     ]

In [48]:
#plot_roc_curve(y_true, probabilities)
def compute_predicted_probabilities(X_data,
                               y_true_labels,
                               model_for_inference,
                               input_text_tokenizer,
                               data_loader_batch_size = 32):
    logits_predictions = compute_predictions(X_data, model_for_inference, input_text_tokenizer, data_loader_batch_size)
    softmax_predictions = torch.softmax(logits_predictions, dim=1)  # Softmax for probabilistic interpretation.
    return softmax_predictions[:, 1]

def compute_predictions(X_data, model_for_inference, input_text_tokenizer, data_loader_batch_size = 32):
    X =list(X_data)
    #Collate function and dataloader for parallel inference
    def collate_input(batch):
        return input_text_tokenizer(batch, return_tensors="pt", padding=True, truncation=True, max_length=512)

    # Use Dataloader class passing as input a List of strings.
    # This is Ok as List provides all required operations that a Dataset would provide for building a DataLoader
    loader = DataLoader(X, batch_size=data_loader_batch_size, collate_fn=collate_input)

    # Perform inference using X data
    #switch pytorch from training mode to evaluation-inference mode. Important to disable train only operations.
    model_for_inference.eval()

    #If available save model in GPU
    inference_device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model_for_inference.to(inference_device)


    all_outputs = []
    with torch.no_grad():
      for inputs in loader:
          inputs = {k: v.to(inference_device) for k, v in inputs.items()} #If available save
                                                                # data in GPU
          logits = model_for_inference(**inputs).logits
          all_outputs.append(logits.detach().cpu())
          del inputs, logits
          torch.cuda.empty_cache()
    gc.collect()
    torch.cuda.empty_cache()
    inference_outputs_tensor = torch.cat(all_outputs, dim=0)


    #switch/restore train mode
    model_for_inference.train()

    return inference_outputs_tensor

In [49]:
grammatical_df_results = compute_predicted_probabilities(
                                     X_data                   = mela_test_all["sentence"],
                                     y_true_labels            = mela_test_all["label"],
                                     model_for_inference = Grammatical_DistilBertLast3LayerFusion_reload,

                                     input_text_tokenizer     = tokenizer)

In [50]:
grammatical_df_results

tensor([0.2005, 0.6067, 0.4264,  ..., 0.5818, 0.5455, 0.3695])

In [51]:
from sklearn.metrics import roc_auc_score, roc_curve

#auc = roc_auc_score(mela_test_all["label"], grammatical_df_results)
#fpr, tpr, thresholds = roc_curve(y_true, y_prob)
#auc

In [52]:
def compute_evaluation_metrics(X_data,
                               y_true_labels,
                               model_for_inference,
                               input_text_tokenizer,
                               data_loader_batch_size = 32,
                               print_report=False,
                               threshold_hp = 0.5):
    logits_predictions = compute_predictions(X_data, model_for_inference, input_text_tokenizer, data_loader_batch_size)
    softmax_predictions = torch.softmax(logits_predictions, dim=1)  # Softmax for probabilistic interpretation.
    return compute_model_metrics(softmax_predictions[:, 1], y_true_labels, print_report=print_report, threshold_hp = threshold_hp)

from sklearn.metrics import confusion_matrix, precision_score, recall_score, f1_score, accuracy_score

def compute_model_metrics(predictions_class_1, y_true, threshold_hp = 0.5, print_report=False):
    """
    :param predictions_class_1: Vector of membership probabilities for Class 1 (that instance belongs to class 1).
    :param y_true:  Vector with correct True labels for each sample in dataset.
    :param threshold_hp: A [0-1] custom [>=] threshhold to assign class 1 membership (Optional with default 0.5).
    :param print_report: If true, prints out all computed metrics including the confusion matrix values. If False, returns a dictionary with name and value of metrics. Useful for metrics post epoch evaluation during training.
    """

    assert (0.0 <= threshold_hp <= 1.0), f"Threshold_hp must be a number in range [0-1]"
    y_pred  = (predictions_class_1 >= threshold_hp).long() # Model predicted classification Class-labels
                                                           # long() casts boolean to Int64 in Tensors


    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    accuracy       = accuracy_score(y_true, y_pred)
    precision      = precision_score(y_true, y_pred)
    recall         = recall_score(y_true, y_pred)  # a.k.a. sensitivity
    specificity    = tn / (tn + fp)
    f1             = f1_score(y_true, y_pred)

    youden_j_statistic   = recall + specificity - 1.0
    fpr, tpr, thresholds = roc_curve(y_true, predictions_class_1)
    roc_auc              = auc(fpr, tpr)

    # https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.pearsonr.html
    # https://en.wikipedia.org/wiki/Pearson_correlation_coefficient
    pearson_correlation_coefficient, p_value = pearsonr(y_true, predictions_class_1)

    if (print_report):
        print("TN =",tn, "FP =",fp, "FN =",fn, "TP =",tp)
        print(f"Accuracy                  : {accuracy:.4f}", " |",tn + tp, "/" ,tn+fp+fn+tp)
        print(f"F1 Score                  : {f1:.4f}")
        print(f"Precision                 : {precision:.4f}", " |",tp, "/" ,tp+fp)
        print(f"Sensitivity (Recall, TPR) : {recall:.4f}", " |", tp, "/" ,tp+fn)
        print(f"Specificity (TNR)         : {specificity:.4f}", " |", tn, "/" ,tn+fp) #
        print(f"Youden's J statistic      : {youden_j_statistic:.4f}")
        print(f"ROC AUC                   : {roc_auc:.4f}")
        print(f"Pearson correlation       : r = {pearson_correlation_coefficient:.4f}", f" p = {p_value}")

        return None
    else:
        results = {
        "Accuracy":accuracy,
        "F1":f1,
        "Precision":precision,
        "Sensitivity (Recall, TPR)":recall,
        "Specificity (TNR)":specificity,
        "Youden's J statistic":youden_j_statistic,
        "ROC AUC":roc_auc,
        "Pearson correlation":pearson_correlation_coefficient
        }
        return results

In [53]:
compute_evaluation_metrics(
                               X_data               =  mela_test_all["sentence"],
                               y_true_labels        =  mela_test_all["label"],
                               model_for_inference  = Grammatical_DistilBertLast3LayerFusion_reload,
                               input_text_tokenizer = tokenizer,
                               data_loader_batch_size = 32,
                               print_report=True)

TN = 1322 FP = 703 FN = 2370 TP = 3026
Accuracy                  : 0.5859  | 4348 / 7421
F1 Score                  : 0.6632
Precision                 : 0.8115  | 3026 / 3729
Sensitivity (Recall, TPR) : 0.5608  | 3026 / 5396
Specificity (TNR)         : 0.6528  | 1322 / 2025
Youden's J statistic      : 0.2136
ROC AUC                   : 0.6468
Pearson correlation       : r = 0.2299  p = 1.4290961789921073e-89

In [55]:
from sklearn.metrics import matthews_corrcoef

y_pred = (grammatical_df_results >= 0.5).long()
mcc = matthews_corrcoef(mela_test_all["label"], y_pred)
mcc

0.19031546393348958